// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Output configuration for BatchTranslateDocument request.
public struct BatchDocumentOutputConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The destination of output. The destination directory provided must exist
  /// and be empty.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `BatchDocumentOutputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchDocumentOutputConfig().with { $0.gcsDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsDestination = "gcsDestination"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsDestination = try container.decodeIfPresent(
      GcsDestination?.self, forKey: .gcsDestination)
    {
      try destinationCheckAndSet(.gcsDestination(gcsDestination))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.destination {
      switch choice {
      case .gcsDestination(let value):
        try container.encode(value, forKey: .gcsDestination)
      }
    }
  }

  /// The destination of output. The destination directory provided must exist
  /// and be empty.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Google Cloud Storage destination for output content.
    /// For every single input document (for example, gs://a/b/c.[extension]), we
    /// generate at most 2 * n output files. (n is the # of target_language_codes
    /// in the BatchTranslateDocumentRequest).
    ///
    /// While the input documents are being processed, we write/update an index
    /// file `index.csv` under `gcs_destination.output_uri_prefix` (for example,
    /// gs://translation_output/index.csv) The index file is generated/updated as
    /// new files are being translated. The format is:
    ///
    /// input_document,target_language_code,translation_output,error_output,
    /// glossary_translation_output,glossary_error_output
    ///
    /// `input_document` is one file we matched using gcs_source.input_uri.
    /// `target_language_code` is provided in the request.
    /// `translation_output` contains the translations. (details provided below)
    /// `error_output` contains the error message during processing of the file.
    /// Both translations_file and errors_file could be empty strings if we have
    /// no content to output.
    /// `glossary_translation_output` and `glossary_error_output` are the
    /// translated output/error when we apply glossaries. They could also be
    /// empty if we have no content to output.
    ///
    /// Once a row is present in index.csv, the input/output matching never
    /// changes. Callers should also expect all the content in input_file are
    /// processed and ready to be consumed (that is, no partial output file is
    /// written).
    ///
    /// Since index.csv will be keeping updated during the process, please make
    /// sure there is no custom retention policy applied on the output bucket
    /// that may avoid file updating.
    /// (https://cloud.google.com/storage/docs/bucket-lock#retention-policy)
    ///
    /// The naming format of translation output files follows (for target
    /// language code [trg]): `translation_output`:
    /// `gs://translation_output/a_b_c_[trg]_translation.[extension]`
    /// `glossary_translation_output`:
    /// `gs://translation_test/a_b_c_[trg]_glossary_translation.[extension]`. The
    /// output document will maintain the same file format as the input document.
    ///
    /// The naming format of error output files follows (for target language code
    /// [trg]): `error_output`: `gs://translation_test/a_b_c_[trg]_errors.txt`
    /// `glossary_error_output`:
    /// `gs://translation_test/a_b_c_[trg]_glossary_translation.txt`. The error
    /// output is a txt file containing error details.
    indirect case gcsDestination(GcsDestination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.BatchDocumentOutputConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
