// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Stored in the
/// [google.longrunning.Operation.response][google.longrunning.Operation.response]
/// field returned by BatchTranslateDocument if at least one document is
/// translated successfully.
///
/// [google.longrunning.Operation.response]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/response(_:)
public struct BatchTranslateDocumentResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Total number of pages to translate in all documents. Documents without
  /// clear page definition (such as XLSX) are not counted.
  public var totalPages: Swift.Int64 = Swift.Int64()

  /// Number of successfully translated pages in all documents. Documents without
  /// clear page definition (such as XLSX) are not counted.
  public var translatedPages: Swift.Int64 = Swift.Int64()

  /// Number of pages that failed to process in all documents. Documents without
  /// clear page definition (such as XLSX) are not counted.
  public var failedPages: Swift.Int64 = Swift.Int64()

  /// Number of billable pages in documents with clear page definition (such as
  /// PDF, DOCX, PPTX)
  public var totalBillablePages: Swift.Int64 = Swift.Int64()

  /// Total number of characters (Unicode codepoints) in all documents.
  public var totalCharacters: Swift.Int64 = Swift.Int64()

  /// Number of successfully translated characters (Unicode codepoints) in all
  /// documents.
  public var translatedCharacters: Swift.Int64 = Swift.Int64()

  /// Number of characters that have failed to process (Unicode codepoints) in
  /// all documents.
  public var failedCharacters: Swift.Int64 = Swift.Int64()

  /// Number of billable characters (Unicode codepoints) in documents without
  /// clear page definition, such as XLSX.
  public var totalBillableCharacters: Swift.Int64 = Swift.Int64()

  /// Time when the operation was submitted.
  public var submitTime: GoogleCloudWKT.Timestamp? = nil

  /// The time when the operation is finished and
  /// [google.longrunning.Operation.done][google.longrunning.Operation.done] is
  /// set to true.
  ///
  /// [google.longrunning.Operation.done]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/done
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchTranslateDocumentResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchTranslateDocumentResponse().with { $0.totalPages = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let totalPages = CodingKeys(stringValue: "totalPages")
    static let translatedPages = CodingKeys(stringValue: "translatedPages")
    static let failedPages = CodingKeys(stringValue: "failedPages")
    static let totalBillablePages = CodingKeys(stringValue: "totalBillablePages")
    static let totalCharacters = CodingKeys(stringValue: "totalCharacters")
    static let translatedCharacters = CodingKeys(stringValue: "translatedCharacters")
    static let failedCharacters = CodingKeys(stringValue: "failedCharacters")
    static let totalBillableCharacters = CodingKeys(stringValue: "totalBillableCharacters")
    static let submitTime = CodingKeys(stringValue: "submitTime")
    static let endTime = CodingKeys(stringValue: "endTime")

    static let _knownKeys: Set<Swift.String> = [
      "totalPages",
      "translatedPages",
      "failedPages",
      "totalBillablePages",
      "totalCharacters",
      "translatedCharacters",
      "failedCharacters",
      "totalBillableCharacters",
      "submitTime",
      "endTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalPages) {
      self.totalPages = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .translatedPages) {
      self.translatedPages = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .failedPages) {
      self.failedPages = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalBillablePages) {
      self.totalBillablePages = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalCharacters) {
      self.totalCharacters = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .translatedCharacters) {
      self.translatedCharacters = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .failedCharacters) {
      self.failedCharacters = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalBillableCharacters)
    {
      self.totalBillableCharacters = value
    }
    self.submitTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .submitTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWKT.Timestamp.self, forKey: .endTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.totalPages, forKey: .totalPages)
    try container.encode(self.translatedPages, forKey: .translatedPages)
    try container.encode(self.failedPages, forKey: .failedPages)
    try container.encode(self.totalBillablePages, forKey: .totalBillablePages)
    try container.encode(self.totalCharacters, forKey: .totalCharacters)
    try container.encode(self.translatedCharacters, forKey: .translatedCharacters)
    try container.encode(self.failedCharacters, forKey: .failedCharacters)
    try container.encode(self.totalBillableCharacters, forKey: .totalBillableCharacters)
    try container.encodeIfPresent(self.submitTime, forKey: .submitTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.BatchTranslateDocumentResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
