// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Stored in the
/// [google.longrunning.Operation.response][google.longrunning.Operation.response]
/// field returned by BatchTranslateText if at least one sentence is translated
/// successfully.
///
/// [google.longrunning.Operation.response]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/response(_:)
public struct BatchTranslateResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Total number of characters (Unicode codepoints).
  public var totalCharacters: Swift.Int64 = Swift.Int64()

  /// Number of successfully translated characters (Unicode codepoints).
  public var translatedCharacters: Swift.Int64 = Swift.Int64()

  /// Number of characters that have failed to process (Unicode codepoints).
  public var failedCharacters: Swift.Int64 = Swift.Int64()

  /// Time when the operation was submitted.
  public var submitTime: GoogleWKT.WKTTimestamp? = nil

  /// The time when the operation is finished and
  /// [google.longrunning.Operation.done][google.longrunning.Operation.done] is
  /// set to true.
  ///
  /// [google.longrunning.Operation.done]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/done
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchTranslateResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchTranslateResponse().with { $0.totalCharacters = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let totalCharacters = CodingKeys(stringValue: "totalCharacters")
    static let translatedCharacters = CodingKeys(stringValue: "translatedCharacters")
    static let failedCharacters = CodingKeys(stringValue: "failedCharacters")
    static let submitTime = CodingKeys(stringValue: "submitTime")
    static let endTime = CodingKeys(stringValue: "endTime")

    static let _knownKeys: Set<Swift.String> = [
      "totalCharacters",
      "translatedCharacters",
      "failedCharacters",
      "submitTime",
      "endTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalCharacters) {
      self.totalCharacters = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .translatedCharacters) {
      self.translatedCharacters = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .failedCharacters) {
      self.failedCharacters = value
    }
    self.submitTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .submitTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.totalCharacters, forKey: .totalCharacters)
    try container.encode(self.translatedCharacters, forKey: .translatedCharacters)
    try container.encode(self.failedCharacters, forKey: .failedCharacters)
    try container.encodeIfPresent(self.submitTime, forKey: .submitTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.BatchTranslateResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
