// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The batch translation request.
public struct BatchTranslateTextRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Location to make a call. Must refer to a caller's project.
  ///
  /// Format: `projects/{project-number-or-id}/locations/{location-id}`.
  ///
  /// The `global` location is not supported for batch translation.
  ///
  /// Only AutoML Translation models or glossaries within the same region (have
  /// the same location-id) can be used, otherwise an INVALID_ARGUMENT (400)
  /// error is returned.
  public var parent: Swift.String = Swift.String()

  /// Required. Source language code. Supported language codes are listed in
  /// [Language
  /// Support](https://cloud.google.com/translate/docs/languages).
  public var sourceLanguageCode: Swift.String = Swift.String()

  /// Required. Specify up to 10 language codes here. Supported language codes
  /// are listed in [Language
  /// Support](https://cloud.google.com/translate/docs/languages).
  public var targetLanguageCodes: [Swift.String] = []

  /// Optional. The models to use for translation. Map's key is target language
  /// code. Map's value is model name. Value can be a built-in general model,
  /// or an AutoML Translation model.
  ///
  /// The value format depends on model type:
  ///
  /// - AutoML Translation models:
  ///   `projects/{project-number-or-id}/locations/{location-id}/models/{model-id}`
  ///
  /// - General (built-in) models:
  ///   `projects/{project-number-or-id}/locations/{location-id}/models/general/nmt`,
  ///
  ///
  /// If the map is empty or a specific model is
  /// not requested for a language pair, then default google model (nmt) is used.
  public var models: [Swift.String: Swift.String] = [:]

  /// Required. Input configurations.
  /// The total number of files matched should be <= 100.
  /// The total content size should be <= 100M Unicode codepoints.
  /// The files must use UTF-8 encoding.
  public var inputConfigs: [InputConfig] = []

  /// Required. Output configuration.
  /// If 2 input configs match to the same file (that is, same input path),
  /// we don't generate output for duplicate inputs.
  public var outputConfig: OutputConfig? = nil

  /// Optional. Glossaries to be applied for translation.
  /// It's keyed by target language code.
  public var glossaries: [Swift.String: TranslateTextGlossaryConfig] = [:]

  /// Optional. The labels with user-defined metadata for the request.
  ///
  /// Label keys and values can be no longer than 63 characters
  /// (Unicode codepoints), can only contain lowercase letters, numeric
  /// characters, underscores and dashes. International characters are allowed.
  /// Label values are optional. Label keys must start with a letter.
  ///
  /// See https://cloud.google.com/translate/docs/advanced/labels for more
  /// information.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchTranslateTextRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchTranslateTextRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let sourceLanguageCode = CodingKeys(stringValue: "sourceLanguageCode")
    static let targetLanguageCodes = CodingKeys(stringValue: "targetLanguageCodes")
    static let models = CodingKeys(stringValue: "models")
    static let inputConfigs = CodingKeys(stringValue: "inputConfigs")
    static let outputConfig = CodingKeys(stringValue: "outputConfig")
    static let glossaries = CodingKeys(stringValue: "glossaries")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "sourceLanguageCode",
      "targetLanguageCodes",
      "models",
      "inputConfigs",
      "outputConfig",
      "glossaries",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceLanguageCode) {
      self.sourceLanguageCode = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .targetLanguageCodes)
    {
      self.targetLanguageCodes = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .models)
    {
      self.models = value
    }
    if let value = try container.decodeIfPresent([InputConfig].self, forKey: .inputConfigs) {
      self.inputConfigs = value
    }
    self.outputConfig = try container.decodeIfPresent(OutputConfig.self, forKey: .outputConfig)
    if let value = try container.decodeIfPresent(
      [Swift.String: TranslateTextGlossaryConfig].self, forKey: .glossaries)
    {
      self.glossaries = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.sourceLanguageCode, forKey: .sourceLanguageCode)
    try container.encode(self.targetLanguageCodes, forKey: .targetLanguageCodes)
    try container.encode(self.models, forKey: .models)
    try container.encode(self.inputConfigs, forKey: .inputConfigs)
    try container.encodeIfPresent(self.outputConfig, forKey: .outputConfig)
    try container.encode(self.glossaries, forKey: .glossaries)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.BatchTranslateTextRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
