// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Input configuration for datasets.
public struct DatasetInputConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Files containing the sentence pairs to be imported to the dataset.
  public var inputFiles: [DatasetInputConfig.InputFile] = []

  /// Initialize a new instance of `DatasetInputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DatasetInputConfig().with { $0.inputFiles = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An input file.
  public struct InputFile: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Usage of the file contents. Options are TRAIN|VALIDATION|TEST,
    /// or UNASSIGNED (by default) for auto split.
    public var usage: Swift.String = Swift.String()

    /// Source of the file containing sentence pairs.
    /// Supported formats are tab-separated values (.tsv) and Translation Memory
    /// eXchange (.tmx) .
    public var source: OneOf_Source? = nil

    /// Initialize a new instance of `InputFile`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InputFile().with { $0.usage = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case usage = "usage"
      case gcsSource = "gcsSource"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.usage = try container.decode(Swift.String.self, forKey: .usage)

      var source: OneOf_Source? = nil
      let sourceCheckAndSet = {
        if source != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'source'"))
        }
        source = $0
      }
      if let gcsSource = try container.decodeIfPresent(GcsInputSource?.self, forKey: .gcsSource) {
        try sourceCheckAndSet(.gcsSource(gcsSource))
      }
      self.source = source
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.usage, forKey: .usage)

      if let choice = self.source {
        switch choice {
        case .gcsSource(let value):
          try container.encode(value, forKey: .gcsSource)
        }
      }
    }

    /// Source of the file containing sentence pairs.
    /// Supported formats are tab-separated values (.tsv) and Translation Memory
    /// eXchange (.tmx) .
    public enum OneOf_Source: Codable, Equatable, Sendable {
      /// Google Cloud Storage file source.
      indirect case gcsSource(GcsInputSource?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.translation.v3.DatasetInputConfig.InputFile"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.DatasetInputConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
