// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A document translation request output config.
public struct DocumentOutputConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Specifies the translated document's mime_type.
  /// If not specified, the translated file's mime type will be the same as the
  /// input file's mime type.
  /// Currently only support the output mime type to be the same as input mime
  /// type.
  /// - application/pdf
  /// - application/vnd.openxmlformats-officedocument.wordprocessingml.document
  /// - application/vnd.openxmlformats-officedocument.presentationml.presentation
  /// - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  public var mimeType: Swift.String = Swift.String()

  /// A URI destination for the translated document.
  /// It is optional to provide a destination. If provided the results from
  /// TranslateDocument will be stored in the destination.
  /// Whether a destination is provided or not, the translated documents will be
  /// returned within TranslateDocumentResponse.document_translation and
  /// TranslateDocumentResponse.glossary_document_translation.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `DocumentOutputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DocumentOutputConfig().with { $0.gcsDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsDestination = "gcsDestination"
    case mimeType = "mimeType"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.mimeType = try container.decode(Swift.String.self, forKey: .mimeType)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsDestination = try container.decodeIfPresent(
      GcsDestination?.self, forKey: .gcsDestination)
    {
      try destinationCheckAndSet(.gcsDestination(gcsDestination))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.mimeType, forKey: .mimeType)

    if let choice = self.destination {
      switch choice {
      case .gcsDestination(let value):
        try container.encode(value, forKey: .gcsDestination)
      }
    }
  }

  /// A URI destination for the translated document.
  /// It is optional to provide a destination. If provided the results from
  /// TranslateDocument will be stored in the destination.
  /// Whether a destination is provided or not, the translated documents will be
  /// returned within TranslateDocumentResponse.document_translation and
  /// TranslateDocumentResponse.glossary_document_translation.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Optional. Google Cloud Storage destination for the translation output,
    /// e.g., `gs://my_bucket/my_directory/`.
    ///
    /// The destination directory provided does not have to be empty, but the
    /// bucket must exist. If a file with the same name as the output file
    /// already exists in the destination an error will be returned.
    ///
    /// For a DocumentInputConfig.contents provided document, the output file
    /// will have the name "output_[trg]_translations.[ext]", where
    /// - [trg] corresponds to the translated file's language code,
    /// - [ext] corresponds to the translated file's extension according to its
    /// mime type.
    ///
    ///
    /// For a DocumentInputConfig.gcs_uri provided document, the output file will
    /// have a name according to its URI. For example: an input file with URI:
    /// `gs://a/b/c.[extension]` stored in a gcs_destination bucket with name
    /// "my_bucket" will have an output URI:
    /// `gs://my_bucket/a_b_c_[trg]_translations.[ext]`, where
    /// - [trg] corresponds to the translated file's language code,
    /// - [ext] corresponds to the translated file's extension according to its
    /// mime type.
    ///
    ///
    /// If the document was directly provided through the request, then the
    /// output document will have the format:
    /// `gs://my_bucket/translated_document_[trg]_translations.[ext]`, where
    /// - [trg] corresponds to the translated file's language code,
    /// - [ext] corresponds to the translated file's extension according to its
    /// mime type.
    ///
    /// If a glossary was provided, then the output URI for the glossary
    /// translation will be equal to the default output URI but have
    /// `glossary_translations` instead of `translations`. For the previous
    /// example, its glossary URI would be:
    /// `gs://my_bucket/a_b_c_[trg]_glossary_translations.[ext]`.
    ///
    /// Thus the max number of output files will be 2 (Translated document,
    /// Glossary translated document).
    ///
    /// Callers should expect no partial outputs. If there is any error during
    /// document translation, no output will be stored in the Cloud Storage
    /// bucket.
    indirect case gcsDestination(GcsDestination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.DocumentOutputConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
