// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A document translation request input config.
public struct DocumentInputConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Specifies the input document's mime_type.
  ///
  /// If not specified it will be determined using the file extension for
  /// gcs_source provided files. For a file provided through bytes content the
  /// mime_type must be provided.
  /// Currently supported mime types are:
  /// - application/pdf
  /// - application/vnd.openxmlformats-officedocument.wordprocessingml.document
  /// - application/vnd.openxmlformats-officedocument.presentationml.presentation
  /// - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  public var mimeType: Swift.String = Swift.String()

  /// Specifies the source for the document's content.
  /// The input file size should be <= 20MB for
  /// - application/vnd.openxmlformats-officedocument.wordprocessingml.document
  /// - application/vnd.openxmlformats-officedocument.presentationml.presentation
  /// - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  /// The input file size should be <= 20MB and the maximum page limit is 20 for
  /// - application/pdf
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `DocumentInputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DocumentInputConfig().with { $0.content = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case content = "content"
    case gcsSource = "gcsSource"
    case mimeType = "mimeType"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.mimeType = try container.decode(Swift.String.self, forKey: .mimeType)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let content = try container.decodeIfPresent(Foundation.Data.self, forKey: .content) {
      try sourceCheckAndSet(.content(content))
    }
    if let gcsSource = try container.decodeIfPresent(GcsSource?.self, forKey: .gcsSource) {
      try sourceCheckAndSet(.gcsSource(gcsSource))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.mimeType, forKey: .mimeType)

    if let choice = self.source {
      switch choice {
      case .content(let value):
        try container.encode(value, forKey: .content)
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      }
    }
  }

  /// Specifies the source for the document's content.
  /// The input file size should be <= 20MB for
  /// - application/vnd.openxmlformats-officedocument.wordprocessingml.document
  /// - application/vnd.openxmlformats-officedocument.presentationml.presentation
  /// - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  /// The input file size should be <= 20MB and the maximum page limit is 20 for
  /// - application/pdf
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Document's content represented as a stream of bytes.
    case content(Foundation.Data)
    /// Google Cloud Storage location. This must be a single file.
    /// For example: gs://example_bucket/example_file.pdf
    indirect case gcsSource(GcsSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.DocumentInputConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
