// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A translated document message.
public struct DocumentTranslation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The array of translated documents. It is expected to be size 1 for now. We
  /// may produce multiple translated documents in the future for other type of
  /// file formats.
  public var byteStreamOutputs: [Foundation.Data] = []

  /// The translated document's mime type.
  public var mimeType: Swift.String = Swift.String()

  /// The detected language for the input document.
  /// If the user did not provide the source language for the input document,
  /// this field will have the language code automatically detected. If the
  /// source language was passed, auto-detection of the language does not occur
  /// and this field is empty.
  public var detectedLanguageCode: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DocumentTranslation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DocumentTranslation().with { $0.byteStreamOutputs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let byteStreamOutputs = CodingKeys(stringValue: "byteStreamOutputs")
    static let mimeType = CodingKeys(stringValue: "mimeType")
    static let detectedLanguageCode = CodingKeys(stringValue: "detectedLanguageCode")

    static let _knownKeys: Set<Swift.String> = [
      "byteStreamOutputs",
      "mimeType",
      "detectedLanguageCode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Foundation.Data].self, forKey: .byteStreamOutputs)
    {
      self.byteStreamOutputs = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mimeType) {
      self.mimeType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .detectedLanguageCode) {
      self.detectedLanguageCode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.byteStreamOutputs, forKey: .byteStreamOutputs)
    try container.encode(self.mimeType, forKey: .mimeType)
    try container.encode(self.detectedLanguageCode, forKey: .detectedLanguageCode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.DocumentTranslation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
