// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The Google Cloud Storage location for the output content.
public struct GcsDestination: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The bucket used in 'output_uri_prefix' must exist and there must
  /// be no files under 'output_uri_prefix'. 'output_uri_prefix' must end with
  /// "/" and start with "gs://". One 'output_uri_prefix' can only be used by one
  /// batch translation job at a time. Otherwise an INVALID_ARGUMENT (400) error
  /// is returned.
  public var outputUriPrefix: Swift.String = Swift.String()

  /// Initialize a new instance of `GcsDestination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsDestination().with { $0.outputUriPrefix = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.GcsDestination"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
