// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The request message for discovering supported languages.
public struct GetSupportedLanguagesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Project or location to make a call. Must refer to a caller's
  /// project.
  ///
  /// Format: `projects/{project-number-or-id}` or
  /// `projects/{project-number-or-id}/locations/{location-id}`.
  ///
  /// For global calls, use `projects/{project-number-or-id}/locations/global` or
  /// `projects/{project-number-or-id}`.
  ///
  /// Non-global location is required for AutoML models.
  ///
  /// Only models within the same region (have same location-id) can be used,
  /// otherwise an INVALID_ARGUMENT (400) error is returned.
  public var parent: Swift.String = Swift.String()

  /// Optional. The language to use to return localized, human readable names
  /// of supported languages. If missing, then display names are not returned
  /// in a response.
  public var displayLanguageCode: Swift.String = Swift.String()

  /// Optional. Get supported languages of this model.
  ///
  /// The format depends on model type:
  ///
  /// - AutoML Translation models:
  ///   `projects/{project-number-or-id}/locations/{location-id}/models/{model-id}`
  ///
  /// - General (built-in) models:
  ///   `projects/{project-number-or-id}/locations/{location-id}/models/general/nmt`,
  ///
  ///
  /// Returns languages supported by the specified model.
  /// If missing, we get supported languages of Google general NMT model.
  public var model: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GetSupportedLanguagesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GetSupportedLanguagesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let displayLanguageCode = CodingKeys(stringValue: "displayLanguageCode")
    static let model = CodingKeys(stringValue: "model")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "displayLanguageCode",
      "model",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayLanguageCode) {
      self.displayLanguageCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
      self.model = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.displayLanguageCode, forKey: .displayLanguageCode)
    try container.encode(self.model, forKey: .model)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.GetSupportedLanguagesRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
