// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a single entry in a glossary.
public struct GlossaryEntry: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the entry.
  /// Format:
  ///   `projects/*/locations/*/glossaries/*/glossaryEntries/*`
  public var name: Swift.String = Swift.String()

  /// Describes the glossary entry.
  public var description: Swift.String = Swift.String()

  /// The different data for the glossary types (Unidirectional, Equivalent term
  /// sets).
  public var data: OneOf_Data? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GlossaryEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GlossaryEntry().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let termsPair = CodingKeys(stringValue: "termsPair")
    static let termsSet = CodingKeys(stringValue: "termsSet")
    static let description = CodingKeys(stringValue: "description")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "termsPair",
      "termsSet",
      "description",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }

    var data: OneOf_Data? = nil
    let dataCheckAndSet = {
      if data != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'data'"
          ))
      }
      data = $0
    }
    if let termsPair = try container.decodeIfPresent(
      GlossaryEntry.GlossaryTermsPair?.self, forKey: .termsPair)
    {
      try dataCheckAndSet(.termsPair(termsPair))
    }
    if let termsSet = try container.decodeIfPresent(
      GlossaryEntry.GlossaryTermsSet?.self, forKey: .termsSet)
    {
      try dataCheckAndSet(.termsSet(termsSet))
    }
    self.data = data
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)

    if let choice = self.data {
      switch choice {
      case .termsPair(let value):
        try container.encode(value, forKey: .termsPair)
      case .termsSet(let value):
        try container.encode(value, forKey: .termsSet)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents a single entry for an unidirectional glossary.
  public struct GlossaryTermsPair: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The source term is the term that will get match in the text,
    public var sourceTerm: GlossaryTerm? = nil

    /// The term that will replace the match source term.
    public var targetTerm: GlossaryTerm? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GlossaryTermsPair`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GlossaryTermsPair().with { $0.sourceTerm = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sourceTerm = CodingKeys(stringValue: "sourceTerm")
      static let targetTerm = CodingKeys(stringValue: "targetTerm")

      static let _knownKeys: Set<Swift.String> = [
        "sourceTerm",
        "targetTerm",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.sourceTerm = try container.decodeIfPresent(GlossaryTerm.self, forKey: .sourceTerm)
      self.targetTerm = try container.decodeIfPresent(GlossaryTerm.self, forKey: .targetTerm)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.sourceTerm, forKey: .sourceTerm)
      try container.encodeIfPresent(self.targetTerm, forKey: .targetTerm)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.translation.v3.GlossaryEntry.GlossaryTermsPair"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents a single entry for an equivalent term set glossary. This is used
  /// for equivalent term sets where each term can be replaced by the other terms
  /// in the set.
  public struct GlossaryTermsSet: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Each term in the set represents a term that can be replaced by the other
    /// terms.
    public var terms: [GlossaryTerm] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GlossaryTermsSet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GlossaryTermsSet().with { $0.terms = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let terms = CodingKeys(stringValue: "terms")

      static let _knownKeys: Set<Swift.String> = [
        "terms"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([GlossaryTerm].self, forKey: .terms) {
        self.terms = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.terms, forKey: .terms)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.translation.v3.GlossaryEntry.GlossaryTermsSet"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The different data for the glossary types (Unidirectional, Equivalent term
  /// sets).
  public enum OneOf_Data: Codable, Equatable, Sendable {
    /// Used for an unidirectional glossary.
    indirect case termsPair(GlossaryEntry.GlossaryTermsPair?)
    /// Used for an equivalent term sets glossary.
    indirect case termsSet(GlossaryEntry.GlossaryTermsSet?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.GlossaryEntry"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
