// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Input configuration for glossaries.
public struct GlossaryInputConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Specify the input.
  public var source: SourceOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GlossaryInputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GlossaryInputConfig().with { $0.gcsSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsSource = CodingKeys(stringValue: "gcsSource")

    static let _knownKeys: Set<Swift.String> = [
      "gcsSource"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var source: SourceOneOf? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsSource = try container.decodeIfPresent(GcsSource?.self, forKey: .gcsSource) {
      try sourceCheckAndSet(.gcsSource(gcsSource))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.source {
      switch choice {
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Required. Specify the input.
  public enum SourceOneOf: Codable, Equatable, Sendable {
    /// Required. Google Cloud Storage location of glossary data.
    /// File format is determined based on the filename extension. API returns
    /// [google.rpc.Code.INVALID_ARGUMENT] for unsupported URI-s and file
    /// formats. Wildcards are not allowed. This must be a single file in one of
    /// the following formats:
    ///
    /// For unidirectional glossaries:
    ///
    /// - TSV/CSV (`.tsv`/`.csv`): Two column file, tab- or comma-separated.
    ///   The first column is source text. The second column is target text.
    ///   No headers in this file. The first row contains data and not column
    ///   names.
    ///
    /// - TMX (`.tmx`): TMX file with parallel data defining source/target term
    /// pairs.
    ///
    /// For equivalent term sets glossaries:
    ///
    /// - CSV (`.csv`): Multi-column CSV file defining equivalent glossary terms
    ///   in multiple languages. See documentation for more information -
    ///   [glossaries](https://cloud.google.com/translate/docs/advanced/glossary).
    indirect case gcsSource(GcsSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.GlossaryInputConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
