// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a glossary built from user-provided data.
public struct Glossary: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the glossary. Glossary names have the form
  /// `projects/{project-number-or-id}/locations/{location-id}/glossaries/{glossary-id}`.
  public var name: Swift.String = Swift.String()

  /// Required. Provides examples to build the glossary from.
  /// Total glossary must not exceed 10M Unicode codepoints.
  public var inputConfig: GlossaryInputConfig? = nil

  /// Output only. The number of entries defined in the glossary.
  public var entryCount: Swift.Int32 = Swift.Int32()

  /// Output only. When CreateGlossary was called.
  public var submitTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the glossary creation was finished.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The display name of the glossary.
  public var displayName: Swift.String = Swift.String()

  /// Languages supported by the glossary.
  public var languages: LanguagesOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Glossary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Glossary().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let languagePair = CodingKeys(stringValue: "languagePair")
    static let languageCodesSet = CodingKeys(stringValue: "languageCodesSet")
    static let inputConfig = CodingKeys(stringValue: "inputConfig")
    static let entryCount = CodingKeys(stringValue: "entryCount")
    static let submitTime = CodingKeys(stringValue: "submitTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let displayName = CodingKeys(stringValue: "displayName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "languagePair",
      "languageCodesSet",
      "inputConfig",
      "entryCount",
      "submitTime",
      "endTime",
      "displayName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.inputConfig = try container.decodeIfPresent(GlossaryInputConfig.self, forKey: .inputConfig)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .entryCount) {
      self.entryCount = value
    }
    self.submitTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .submitTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }

    var languages: LanguagesOneOf? = nil
    let languagesCheckAndSet = {
      if languages != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'languages'"))
      }
      languages = $0
    }
    if let languagePair = try container.decodeIfPresent(
      Glossary.LanguageCodePair?.self, forKey: .languagePair)
    {
      try languagesCheckAndSet(.languagePair(languagePair))
    }
    if let languageCodesSet = try container.decodeIfPresent(
      Glossary.LanguageCodesSet?.self, forKey: .languageCodesSet)
    {
      try languagesCheckAndSet(.languageCodesSet(languageCodesSet))
    }
    self.languages = languages
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.inputConfig, forKey: .inputConfig)
    try container.encode(self.entryCount, forKey: .entryCount)
    try container.encodeIfPresent(self.submitTime, forKey: .submitTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.displayName, forKey: .displayName)

    if let choice = self.languages {
      switch choice {
      case .languagePair(let value):
        try container.encode(value, forKey: .languagePair)
      case .languageCodesSet(let value):
        try container.encode(value, forKey: .languageCodesSet)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Used with unidirectional glossaries.
  public struct LanguageCodePair: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The ISO-639 language code of the input text, for example,
    /// "en-US". Expected to be an exact match for GlossaryTerm.language_code.
    public var sourceLanguageCode: Swift.String = Swift.String()

    /// Required. The ISO-639 language code for translation output, for example,
    /// "zh-CN". Expected to be an exact match for GlossaryTerm.language_code.
    public var targetLanguageCode: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LanguageCodePair`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LanguageCodePair().with { $0.sourceLanguageCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sourceLanguageCode = CodingKeys(stringValue: "sourceLanguageCode")
      static let targetLanguageCode = CodingKeys(stringValue: "targetLanguageCode")

      static let _knownKeys: Set<Swift.String> = [
        "sourceLanguageCode",
        "targetLanguageCode",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceLanguageCode) {
        self.sourceLanguageCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetLanguageCode) {
        self.targetLanguageCode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sourceLanguageCode, forKey: .sourceLanguageCode)
      try container.encode(self.targetLanguageCode, forKey: .targetLanguageCode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.translation.v3.Glossary.LanguageCodePair"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Used with equivalent term set glossaries.
  public struct LanguageCodesSet: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The ISO-639 language code(s) for terms defined in the glossary.
    /// All entries are unique. The list contains at least two entries.
    /// Expected to be an exact match for GlossaryTerm.language_code.
    public var languageCodes: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LanguageCodesSet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LanguageCodesSet().with { $0.languageCodes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let languageCodes = CodingKeys(stringValue: "languageCodes")

      static let _knownKeys: Set<Swift.String> = [
        "languageCodes"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .languageCodes) {
        self.languageCodes = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.languageCodes, forKey: .languageCodes)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.translation.v3.Glossary.LanguageCodesSet"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Languages supported by the glossary.
  public enum LanguagesOneOf: Codable, Equatable, Sendable {
    /// Used with unidirectional glossaries.
    indirect case languagePair(Glossary.LanguageCodePair?)
    /// Used with equivalent term set glossaries.
    indirect case languageCodesSet(Glossary.LanguageCodesSet?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.Glossary"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
