// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Input configuration for BatchTranslateText request.
public struct InputConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Can be "text/plain" or "text/html".
  /// For `.tsv`, "text/html" is used if mime_type is missing.
  /// For `.html`, this field must be "text/html" or empty.
  /// For `.txt`, this field must be "text/plain" or empty.
  public var mimeType: Swift.String = Swift.String()

  /// Required. Specify the input.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InputConfig().with { $0.mimeType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let mimeType = CodingKeys(stringValue: "mimeType")
    static let gcsSource = CodingKeys(stringValue: "gcsSource")

    static let _knownKeys: Set<Swift.String> = [
      "mimeType",
      "gcsSource",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mimeType) {
      self.mimeType = value
    }

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsSource = try container.decodeIfPresent(GcsSource?.self, forKey: .gcsSource) {
      try sourceCheckAndSet(.gcsSource(gcsSource))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.mimeType, forKey: .mimeType)

    if let choice = self.source {
      switch choice {
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Required. Specify the input.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Required. Google Cloud Storage location for the source input.
    /// This can be a single file (for example,
    /// `gs://translation-test/input.tsv`) or a wildcard (for example,
    /// `gs://translation-test/*`). If a file extension is `.tsv`, it can
    /// contain either one or two columns. The first column (optional) is the id
    /// of the text request. If the first column is missing, we use the row
    /// number (0-based) from the input file as the ID in the output file. The
    /// second column is the actual text to be
    ///  translated. We recommend each row be <= 10K Unicode codepoints,
    /// otherwise an error might be returned.
    /// Note that the input tsv must be RFC 4180 compliant.
    ///
    /// You could use https://github.com/Clever/csvlint to check potential
    /// formatting errors in your tsv file.
    /// csvlint --delimiter='\t' your_input_file.tsv
    ///
    /// The other supported file extensions are `.txt` or `.html`, which is
    /// treated as a single large chunk of text.
    indirect case gcsSource(GcsSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.InputConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
