// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for ListGlossaries.
public struct ListGlossariesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the project from which to list all of the glossaries.
  public var parent: Swift.String = Swift.String()

  /// Optional. Requested page size. The server may return fewer glossaries than
  /// requested. If unspecified, the server picks an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying a page of results the server should return.
  /// Typically, this is the value of [ListGlossariesResponse.next_page_token]
  /// returned from the previous call to `ListGlossaries` method.
  /// The first page is returned if `page_token`is empty or missing.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Filter specifying constraints of a list operation.
  /// Specify the constraint by the format of "key=value", where key must be
  /// "src" or "tgt", and the value must be a valid language code.
  /// For multiple restrictions, concatenate them by "AND" (uppercase only),
  /// such as: "src=en-US AND tgt=zh-CN". Notice that the exact match is used
  /// here, which means using 'en-US' and 'en' can lead to different results,
  /// which depends on the language code you used when you create the glossary.
  /// For the unidirectional glossaries, the "src" and "tgt" add restrictions
  /// on the source and target language code separately.
  /// For the equivalent term set glossaries, the "src" and/or "tgt" add
  /// restrictions on the term set.
  /// For example: "src=en-US AND tgt=zh-CN" will only pick the unidirectional
  /// glossaries which exactly match the source language code as "en-US" and the
  /// target language code "zh-CN", but all equivalent term set glossaries which
  /// contain "en-US" and "zh-CN" in their language set will be picked.
  /// If missing, no filtering is performed.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListGlossariesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListGlossariesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.ListGlossariesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
