// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// The response for listing all AdaptiveMt files under a given dataset.
public struct ListAdaptiveMtFilesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// Output only. The Adaptive MT files.
  public var adaptiveMtFiles: [AdaptiveMtFile] = []

  /// Optional. A token to retrieve a page of results. Pass this value in the
  /// ListAdaptiveMtFilesRequest.page_token field in the subsequent call to
  /// `ListAdaptiveMtFiles` method to retrieve the next page of results.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAdaptiveMtFilesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAdaptiveMtFilesResponse().with { $0.adaptiveMtFiles = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.ListAdaptiveMtFilesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [AdaptiveMtFile] {
    return self.adaptiveMtFiles
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
