// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A trained translation model.
public struct Model: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the model, in form of
  /// `projects/{project-number-or-id}/locations/{location_id}/models/{model_id}`
  public var name: Swift.String = Swift.String()

  /// The name of the model to show in the interface. The name can be
  /// up to 32 characters long and can consist only of ASCII Latin letters A-Z
  /// and a-z, underscores (_), and ASCII digits 0-9.
  public var displayName: Swift.String = Swift.String()

  /// The dataset from which the model is trained, in form of
  /// `projects/{project-number-or-id}/locations/{location_id}/datasets/{dataset_id}`
  public var dataset: Swift.String = Swift.String()

  /// Output only. The BCP-47 language code of the source language.
  public var sourceLanguageCode: Swift.String = Swift.String()

  /// Output only. The BCP-47 language code of the target language.
  public var targetLanguageCode: Swift.String = Swift.String()

  /// Output only. Number of examples (sentence pairs) used to train the model.
  public var trainExampleCount: Swift.Int32 = Swift.Int32()

  /// Output only. Number of examples (sentence pairs) used to validate the
  /// model.
  public var validateExampleCount: Swift.Int32 = Swift.Int32()

  /// Output only. Number of examples (sentence pairs) used to test the model.
  public var testExampleCount: Swift.Int32 = Swift.Int32()

  /// Output only. Timestamp when the model resource was created, which is also
  /// when the training started.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Timestamp when this model was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `Model`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Model().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.Model"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
