// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request message for synchronous romanization.
public struct RomanizeTextRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Project or location to make a call. Must refer to a caller's
  /// project.
  ///
  /// Format: `projects/{project-number-or-id}/locations/{location-id}` or
  /// `projects/{project-number-or-id}`.
  ///
  /// For global calls, use `projects/{project-number-or-id}/locations/global` or
  /// `projects/{project-number-or-id}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The content of the input in string format.
  public var contents: [Swift.String] = []

  /// Optional. The ISO-639 language code of the input text if
  /// known, for example, "hi" or "zh". Supported language codes are
  /// listed in [Language
  /// Support](https://cloud.google.com/translate/docs/languages#roman). If the
  /// source language isn't specified, the API attempts to identify the source
  /// language automatically and returns the source language for each content in
  /// the response.
  public var sourceLanguageCode: Swift.String = Swift.String()

  /// Initialize a new instance of `RomanizeTextRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RomanizeTextRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.RomanizeTextRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
