// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A single supported language response corresponds to information related
/// to one supported language.
public struct SupportedLanguage: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Supported language code, generally consisting of its ISO 639-1
  /// identifier, for example, 'en', 'ja'. In certain cases, ISO-639 codes
  /// including language and region identifiers are returned (for example,
  /// 'zh-TW' and 'zh-CN').
  public var languageCode: Swift.String = Swift.String()

  /// Human-readable name of the language localized in the display language
  /// specified in the request.
  public var displayName: Swift.String = Swift.String()

  /// Can be used as a source language.
  public var supportSource: Swift.Bool = Swift.Bool()

  /// Can be used as a target language.
  public var supportTarget: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SupportedLanguage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SupportedLanguage().with { $0.languageCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let languageCode = CodingKeys(stringValue: "languageCode")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let supportSource = CodingKeys(stringValue: "supportSource")
    static let supportTarget = CodingKeys(stringValue: "supportTarget")

    static let _knownKeys: Set<Swift.String> = [
      "languageCode",
      "displayName",
      "supportSource",
      "supportTarget",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
      self.languageCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .supportSource) {
      self.supportSource = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .supportTarget) {
      self.supportTarget = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.languageCode, forKey: .languageCode)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.supportSource, forKey: .supportSource)
    try container.encode(self.supportTarget, forKey: .supportTarget)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.SupportedLanguage"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
