// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol TranslationServiceStub: Sendable {
    func translateText(
      request: TranslateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.TranslateTextResponse

    func romanizeText(
      request: RomanizeTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.RomanizeTextResponse

    func detectLanguage(
      request: DetectLanguageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.DetectLanguageResponse

    func getSupportedLanguages(
      request: GetSupportedLanguagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.SupportedLanguages

    func translateDocument(
      request: TranslateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.TranslateDocumentResponse

    func batchTranslateText(
      request: BatchTranslateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func batchTranslateDocument(
      request: BatchTranslateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createGlossary(
      request: CreateGlossaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateGlossary(
      request: UpdateGlossaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listGlossaries(
      request: ListGlossariesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListGlossariesResponse

    func getGlossary(
      request: GetGlossaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Glossary

    func deleteGlossary(
      request: DeleteGlossaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getGlossaryEntry(
      request: GetGlossaryEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry

    func listGlossaryEntries(
      request: ListGlossaryEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse

    func createGlossaryEntry(
      request: CreateGlossaryEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry

    func updateGlossaryEntry(
      request: UpdateGlossaryEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry

    func deleteGlossaryEntry(
      request: DeleteGlossaryEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createDataset(
      request: CreateDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getDataset(
      request: GetDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Dataset

    func listDatasets(
      request: ListDatasetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListDatasetsResponse

    func deleteDataset(
      request: DeleteDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createAdaptiveMtDataset(
      request: CreateAdaptiveMtDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset

    func deleteAdaptiveMtDataset(
      request: DeleteAdaptiveMtDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getAdaptiveMtDataset(
      request: GetAdaptiveMtDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset

    func listAdaptiveMtDatasets(
      request: ListAdaptiveMtDatasetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse

    func adaptiveMtTranslate(
      request: AdaptiveMtTranslateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse

    func getAdaptiveMtFile(
      request: GetAdaptiveMtFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtFile

    func deleteAdaptiveMtFile(
      request: DeleteAdaptiveMtFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func importAdaptiveMtFile(
      request: ImportAdaptiveMtFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse

    func listAdaptiveMtFiles(
      request: ListAdaptiveMtFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse

    func listAdaptiveMtSentences(
      request: ListAdaptiveMtSentencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse

    func importData(
      request: ImportDataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportData(
      request: ExportDataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listExamples(
      request: ListExamplesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListExamplesResponse

    func createModel(
      request: CreateModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listModels(
      request: ListModelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListModelsResponse

    func getModel(
      request: GetModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Model

    func deleteModel(
      request: DeleteModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
