// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A single translation response.
public struct Translation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Text translated into the target language.
  /// If an error occurs during translation, this field might be excluded from
  /// the response.
  public var translatedText: Swift.String = Swift.String()

  /// Only present when `model` is present in the request.
  /// `model` here is normalized to have project number.
  ///
  /// For example:
  /// If the `model` requested in TranslationTextRequest is
  /// `projects/{project-id}/locations/{location-id}/models/general/nmt` then
  /// `model` here would be normalized to
  /// `projects/{project-number}/locations/{location-id}/models/general/nmt`.
  public var model: Swift.String = Swift.String()

  /// The ISO-639 language code of source text in the initial request, detected
  /// automatically, if no source language was passed within the initial
  /// request. If the source language was passed, auto-detection of the language
  /// does not occur and this field is empty.
  public var detectedLanguageCode: Swift.String = Swift.String()

  /// The `glossary_config` used for this translation.
  public var glossaryConfig: TranslateTextGlossaryConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Translation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Translation().with { $0.translatedText = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let translatedText = CodingKeys(stringValue: "translatedText")
    static let model = CodingKeys(stringValue: "model")
    static let detectedLanguageCode = CodingKeys(stringValue: "detectedLanguageCode")
    static let glossaryConfig = CodingKeys(stringValue: "glossaryConfig")

    static let _knownKeys: Set<Swift.String> = [
      "translatedText",
      "model",
      "detectedLanguageCode",
      "glossaryConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .translatedText) {
      self.translatedText = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
      self.model = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .detectedLanguageCode) {
      self.detectedLanguageCode = value
    }
    self.glossaryConfig = try container.decodeIfPresent(
      TranslateTextGlossaryConfig.self, forKey: .glossaryConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.translatedText, forKey: .translatedText)
    try container.encode(self.model, forKey: .model)
    try container.encode(self.detectedLanguageCode, forKey: .detectedLanguageCode)
    try container.encodeIfPresent(self.glossaryConfig, forKey: .glossaryConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.Translation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
