// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class TranslationServiceRetry: TranslationServiceStub {
    let inner: any TranslationServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any TranslationServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func translateText(
      request: TranslateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.TranslateTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: TranslateTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.TranslateTextResponse
          in
          return try await self.inner.translateText(request: r, options: o)
        })
    }

    public func romanizeText(
      request: RomanizeTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.RomanizeTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RomanizeTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.RomanizeTextResponse
          in
          return try await self.inner.romanizeText(request: r, options: o)
        })
    }

    public func detectLanguage(
      request: DetectLanguageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.DetectLanguageResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DetectLanguageRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.DetectLanguageResponse
          in
          return try await self.inner.detectLanguage(request: r, options: o)
        })
    }

    public func getSupportedLanguages(
      request: GetSupportedLanguagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.SupportedLanguages {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSupportedLanguagesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.SupportedLanguages
          in
          return try await self.inner.getSupportedLanguages(request: r, options: o)
        })
    }

    public func translateDocument(
      request: TranslateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.TranslateDocumentResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: TranslateDocumentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.TranslateDocumentResponse
          in
          return try await self.inner.translateDocument(request: r, options: o)
        })
    }

    public func batchTranslateText(
      request: BatchTranslateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchTranslateTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchTranslateText(request: r, options: o)
        })
    }

    public func batchTranslateDocument(
      request: BatchTranslateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchTranslateDocumentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchTranslateDocument(request: r, options: o)
        })
    }

    public func createGlossary(
      request: CreateGlossaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGlossaryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGlossary(request: r, options: o)
        })
    }

    public func updateGlossary(
      request: UpdateGlossaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateGlossaryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGlossary(request: r, options: o)
        })
    }

    public func listGlossaries(
      request: ListGlossariesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListGlossariesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGlossariesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListGlossariesResponse
          in
          return try await self.inner.listGlossaries(request: r, options: o)
        })
    }

    public func getGlossary(
      request: GetGlossaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Glossary {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGlossaryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.Glossary
          in
          return try await self.inner.getGlossary(request: r, options: o)
        })
    }

    public func deleteGlossary(
      request: DeleteGlossaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteGlossaryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGlossary(request: r, options: o)
        })
    }

    public func getGlossaryEntry(
      request: GetGlossaryEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGlossaryEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.GlossaryEntry
          in
          return try await self.inner.getGlossaryEntry(request: r, options: o)
        })
    }

    public func listGlossaryEntries(
      request: ListGlossaryEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGlossaryEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse
          in
          return try await self.inner.listGlossaryEntries(request: r, options: o)
        })
    }

    public func createGlossaryEntry(
      request: CreateGlossaryEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGlossaryEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.GlossaryEntry
          in
          return try await self.inner.createGlossaryEntry(request: r, options: o)
        })
    }

    public func updateGlossaryEntry(
      request: UpdateGlossaryEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateGlossaryEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.GlossaryEntry
          in
          return try await self.inner.updateGlossaryEntry(request: r, options: o)
        })
    }

    public func deleteGlossaryEntry(
      request: DeleteGlossaryEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteGlossaryEntryRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteGlossaryEntry(request: r, options: o)
        })
    }

    public func createDataset(
      request: CreateDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDataset(request: r, options: o)
        })
    }

    public func getDataset(
      request: GetDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Dataset {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.Dataset
          in
          return try await self.inner.getDataset(request: r, options: o)
        })
    }

    public func listDatasets(
      request: ListDatasetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListDatasetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDatasetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListDatasetsResponse
          in
          return try await self.inner.listDatasets(request: r, options: o)
        })
    }

    public func deleteDataset(
      request: DeleteDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDataset(request: r, options: o)
        })
    }

    public func createAdaptiveMtDataset(
      request: CreateAdaptiveMtDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAdaptiveMtDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.AdaptiveMtDataset
          in
          return try await self.inner.createAdaptiveMtDataset(request: r, options: o)
        })
    }

    public func deleteAdaptiveMtDataset(
      request: DeleteAdaptiveMtDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAdaptiveMtDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteAdaptiveMtDataset(request: r, options: o)
        })
    }

    public func getAdaptiveMtDataset(
      request: GetAdaptiveMtDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAdaptiveMtDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.AdaptiveMtDataset
          in
          return try await self.inner.getAdaptiveMtDataset(request: r, options: o)
        })
    }

    public func listAdaptiveMtDatasets(
      request: ListAdaptiveMtDatasetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAdaptiveMtDatasetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse
          in
          return try await self.inner.listAdaptiveMtDatasets(request: r, options: o)
        })
    }

    public func adaptiveMtTranslate(
      request: AdaptiveMtTranslateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AdaptiveMtTranslateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse
          in
          return try await self.inner.adaptiveMtTranslate(request: r, options: o)
        })
    }

    public func getAdaptiveMtFile(
      request: GetAdaptiveMtFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtFile {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAdaptiveMtFileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.AdaptiveMtFile
          in
          return try await self.inner.getAdaptiveMtFile(request: r, options: o)
        })
    }

    public func deleteAdaptiveMtFile(
      request: DeleteAdaptiveMtFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAdaptiveMtFileRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAdaptiveMtFile(request: r, options: o)
        })
    }

    public func importAdaptiveMtFile(
      request: ImportAdaptiveMtFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ImportAdaptiveMtFileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse
          in
          return try await self.inner.importAdaptiveMtFile(request: r, options: o)
        })
    }

    public func listAdaptiveMtFiles(
      request: ListAdaptiveMtFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAdaptiveMtFilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse
          in
          return try await self.inner.listAdaptiveMtFiles(request: r, options: o)
        })
    }

    public func listAdaptiveMtSentences(
      request: ListAdaptiveMtSentencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAdaptiveMtSentencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse
          in
          return try await self.inner.listAdaptiveMtSentences(request: r, options: o)
        })
    }

    public func importData(
      request: ImportDataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ImportDataRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importData(request: r, options: o)
        })
    }

    public func exportData(
      request: ExportDataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportDataRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportData(request: r, options: o)
        })
    }

    public func listExamples(
      request: ListExamplesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListExamplesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListExamplesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListExamplesResponse
          in
          return try await self.inner.listExamples(request: r, options: o)
        })
    }

    public func createModel(
      request: CreateModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createModel(request: r, options: o)
        })
    }

    public func listModels(
      request: ListModelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListModelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListModelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListModelsResponse
          in
          return try await self.inner.listModels(request: r, options: o)
        })
    }

    public func getModel(
      request: GetModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Model {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.Model
          in
          return try await self.inner.getModel(request: r, options: o)
        })
    }

    public func deleteModel(
      request: DeleteModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteModel(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }

    public func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.WaitOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.waitOperation(request: r, options: o)
        })
    }
  }
}
