// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class TranslationServiceLogging: TranslationServiceStub {
    let inner: any TranslationServiceStub
    let logger: Logger

    public init(_ inner: any TranslationServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-translation-v3"
      logger[metadataKey: "gcp.client.service"] = "translate"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TranslationService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func translateText(
      request: TranslateTextRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.TranslateTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "translateText",
        action: {
          (r: TranslateTextRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.TranslateTextResponse
          in
          return try await self.inner.translateText(request: r, options: o)
        })
    }

    public func romanizeText(
      request: RomanizeTextRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.RomanizeTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "romanizeText",
        action: {
          (r: RomanizeTextRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.RomanizeTextResponse
          in
          return try await self.inner.romanizeText(request: r, options: o)
        })
    }

    public func detectLanguage(
      request: DetectLanguageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.DetectLanguageResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "detectLanguage",
        action: {
          (r: DetectLanguageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.DetectLanguageResponse
          in
          return try await self.inner.detectLanguage(request: r, options: o)
        })
    }

    public func getSupportedLanguages(
      request: GetSupportedLanguagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.SupportedLanguages {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSupportedLanguages",
        action: {
          (r: GetSupportedLanguagesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.SupportedLanguages
          in
          return try await self.inner.getSupportedLanguages(request: r, options: o)
        })
    }

    public func translateDocument(
      request: TranslateDocumentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.TranslateDocumentResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "translateDocument",
        action: {
          (r: TranslateDocumentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.TranslateDocumentResponse
          in
          return try await self.inner.translateDocument(request: r, options: o)
        })
    }

    public func batchTranslateText(
      request: BatchTranslateTextRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchTranslateText",
        action: {
          (r: BatchTranslateTextRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchTranslateText(request: r, options: o)
        })
    }

    public func batchTranslateDocument(
      request: BatchTranslateDocumentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchTranslateDocument",
        action: {
          (r: BatchTranslateDocumentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchTranslateDocument(request: r, options: o)
        })
    }

    public func createGlossary(
      request: CreateGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createGlossary",
        action: {
          (r: CreateGlossaryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGlossary(request: r, options: o)
        })
    }

    public func updateGlossary(
      request: UpdateGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateGlossary",
        action: {
          (r: UpdateGlossaryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGlossary(request: r, options: o)
        })
    }

    public func listGlossaries(
      request: ListGlossariesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListGlossariesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGlossaries",
        action: {
          (r: ListGlossariesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListGlossariesResponse
          in
          return try await self.inner.listGlossaries(request: r, options: o)
        })
    }

    public func getGlossary(
      request: GetGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Glossary {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGlossary",
        action: {
          (r: GetGlossaryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.Glossary
          in
          return try await self.inner.getGlossary(request: r, options: o)
        })
    }

    public func deleteGlossary(
      request: DeleteGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteGlossary",
        action: {
          (r: DeleteGlossaryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGlossary(request: r, options: o)
        })
    }

    public func getGlossaryEntry(
      request: GetGlossaryEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGlossaryEntry",
        action: {
          (r: GetGlossaryEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.GlossaryEntry
          in
          return try await self.inner.getGlossaryEntry(request: r, options: o)
        })
    }

    public func listGlossaryEntries(
      request: ListGlossaryEntriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGlossaryEntries",
        action: {
          (r: ListGlossaryEntriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse
          in
          return try await self.inner.listGlossaryEntries(request: r, options: o)
        })
    }

    public func createGlossaryEntry(
      request: CreateGlossaryEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
      try await self._intercept(
        request: request,
        options: options,
        name: "createGlossaryEntry",
        action: {
          (r: CreateGlossaryEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.GlossaryEntry
          in
          return try await self.inner.createGlossaryEntry(request: r, options: o)
        })
    }

    public func updateGlossaryEntry(
      request: UpdateGlossaryEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateGlossaryEntry",
        action: {
          (r: UpdateGlossaryEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.GlossaryEntry
          in
          return try await self.inner.updateGlossaryEntry(request: r, options: o)
        })
    }

    public func deleteGlossaryEntry(
      request: DeleteGlossaryEntryRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteGlossaryEntry",
        action: {
          (r: DeleteGlossaryEntryRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteGlossaryEntry(request: r, options: o)
        })
    }

    public func createDataset(
      request: CreateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDataset",
        action: {
          (r: CreateDatasetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDataset(request: r, options: o)
        })
    }

    public func getDataset(
      request: GetDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Dataset {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDataset",
        action: {
          (r: GetDatasetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.Dataset
          in
          return try await self.inner.getDataset(request: r, options: o)
        })
    }

    public func listDatasets(
      request: ListDatasetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListDatasetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDatasets",
        action: {
          (r: ListDatasetsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListDatasetsResponse
          in
          return try await self.inner.listDatasets(request: r, options: o)
        })
    }

    public func deleteDataset(
      request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDataset",
        action: {
          (r: DeleteDatasetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDataset(request: r, options: o)
        })
    }

    public func createAdaptiveMtDataset(
      request: CreateAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAdaptiveMtDataset",
        action: {
          (r: CreateAdaptiveMtDatasetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.AdaptiveMtDataset
          in
          return try await self.inner.createAdaptiveMtDataset(request: r, options: o)
        })
    }

    public func deleteAdaptiveMtDataset(
      request: DeleteAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAdaptiveMtDataset",
        action: {
          (r: DeleteAdaptiveMtDatasetRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAdaptiveMtDataset(request: r, options: o)
        })
    }

    public func getAdaptiveMtDataset(
      request: GetAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAdaptiveMtDataset",
        action: {
          (r: GetAdaptiveMtDatasetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.AdaptiveMtDataset
          in
          return try await self.inner.getAdaptiveMtDataset(request: r, options: o)
        })
    }

    public func listAdaptiveMtDatasets(
      request: ListAdaptiveMtDatasetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAdaptiveMtDatasets",
        action: {
          (r: ListAdaptiveMtDatasetsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse
          in
          return try await self.inner.listAdaptiveMtDatasets(request: r, options: o)
        })
    }

    public func adaptiveMtTranslate(
      request: AdaptiveMtTranslateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "adaptiveMtTranslate",
        action: {
          (r: AdaptiveMtTranslateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse
          in
          return try await self.inner.adaptiveMtTranslate(request: r, options: o)
        })
    }

    public func getAdaptiveMtFile(
      request: GetAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtFile {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAdaptiveMtFile",
        action: {
          (r: GetAdaptiveMtFileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.AdaptiveMtFile
          in
          return try await self.inner.getAdaptiveMtFile(request: r, options: o)
        })
    }

    public func deleteAdaptiveMtFile(
      request: DeleteAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAdaptiveMtFile",
        action: {
          (r: DeleteAdaptiveMtFileRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAdaptiveMtFile(request: r, options: o)
        })
    }

    public func importAdaptiveMtFile(
      request: ImportAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "importAdaptiveMtFile",
        action: {
          (r: ImportAdaptiveMtFileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse
          in
          return try await self.inner.importAdaptiveMtFile(request: r, options: o)
        })
    }

    public func listAdaptiveMtFiles(
      request: ListAdaptiveMtFilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAdaptiveMtFiles",
        action: {
          (r: ListAdaptiveMtFilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse
          in
          return try await self.inner.listAdaptiveMtFiles(request: r, options: o)
        })
    }

    public func listAdaptiveMtSentences(
      request: ListAdaptiveMtSentencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAdaptiveMtSentences",
        action: {
          (r: ListAdaptiveMtSentencesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse
          in
          return try await self.inner.listAdaptiveMtSentences(request: r, options: o)
        })
    }

    public func importData(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "importData",
        action: {
          (r: ImportDataRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importData(request: r, options: o)
        })
    }

    public func exportData(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportData",
        action: {
          (r: ExportDataRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportData(request: r, options: o)
        })
    }

    public func listExamples(
      request: ListExamplesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListExamplesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listExamples",
        action: {
          (r: ListExamplesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListExamplesResponse
          in
          return try await self.inner.listExamples(request: r, options: o)
        })
    }

    public func createModel(
      request: CreateModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createModel",
        action: {
          (r: CreateModelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createModel(request: r, options: o)
        })
    }

    public func listModels(
      request: ListModelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListModelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listModels",
        action: {
          (r: ListModelsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.ListModelsResponse
          in
          return try await self.inner.listModels(request: r, options: o)
        })
    }

    public func getModel(
      request: GetModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Model {
      try await self._intercept(
        request: request,
        options: options,
        name: "getModel",
        action: {
          (r: GetModelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTranslateV3.Model
          in
          return try await self.inner.getModel(request: r, options: o)
        })
    }

    public func deleteModel(
      request: DeleteModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteModel",
        action: {
          (r: DeleteModelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteModel(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }

    public func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "waitOperation",
        action: {
          (r: GoogleLongRunning.WaitOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.waitOperation(request: r, options: o)
        })
    }
  }
}
