// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A document translation request.
public struct TranslateDocumentRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Location to make a regional call.
  ///
  /// Format: `projects/{project-number-or-id}/locations/{location-id}`.
  ///
  /// For global calls, use `projects/{project-number-or-id}/locations/global` or
  /// `projects/{project-number-or-id}`.
  ///
  /// Non-global location is required for requests using AutoML models or custom
  /// glossaries.
  ///
  /// Models and glossaries must be within the same region (have the same
  /// location-id), otherwise an INVALID_ARGUMENT (400) error is returned.
  public var parent: Swift.String = Swift.String()

  /// Optional. The ISO-639 language code of the input document if known, for
  /// example, "en-US" or "sr-Latn". Supported language codes are listed in
  /// [Language Support](https://cloud.google.com/translate/docs/languages). If
  /// the source language isn't specified, the API attempts to identify the
  /// source language automatically and returns the source language within the
  /// response. Source language must be specified if the request contains a
  /// glossary or a custom model.
  public var sourceLanguageCode: Swift.String = Swift.String()

  /// Required. The ISO-639 language code to use for translation of the input
  /// document, set to one of the language codes listed in [Language
  /// Support](https://cloud.google.com/translate/docs/languages).
  public var targetLanguageCode: Swift.String = Swift.String()

  /// Required. Input configurations.
  public var documentInputConfig: DocumentInputConfig? = nil

  /// Optional. Output configurations.
  /// Defines if the output file should be stored within Cloud Storage as well
  /// as the desired output format. If not provided the translated file will
  /// only be returned through a byte-stream and its output mime type will be
  /// the same as the input file's mime type.
  public var documentOutputConfig: DocumentOutputConfig? = nil

  /// Optional. The `model` type requested for this translation.
  ///
  /// The format depends on model type:
  ///
  /// - AutoML Translation models:
  ///   `projects/{project-number-or-id}/locations/{location-id}/models/{model-id}`
  ///
  /// - General (built-in) models:
  ///   `projects/{project-number-or-id}/locations/{location-id}/models/general/nmt`,
  ///
  ///
  /// If not provided, the default Google model (NMT) will be used for
  /// translation.
  public var model: Swift.String = Swift.String()

  /// Optional. Glossary to be applied. The glossary must be within the same
  /// region (have the same location-id) as the model, otherwise an
  /// INVALID_ARGUMENT (400) error is returned.
  public var glossaryConfig: TranslateTextGlossaryConfig? = nil

  /// Optional. The labels with user-defined metadata for the request.
  ///
  /// Label keys and values can be no longer than 63 characters (Unicode
  /// codepoints), can only contain lowercase letters, numeric characters,
  /// underscores and dashes. International characters are allowed. Label values
  /// are optional. Label keys must start with a letter.
  ///
  /// See https://cloud.google.com/translate/docs/advanced/labels for more
  /// information.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. This flag is to support user customized attribution.
  /// If not provided, the default is `Machine Translated by Google`.
  /// Customized attribution should follow rules in
  /// https://cloud.google.com/translate/attribution#attribution_and_logos
  public var customizedAttribution: Swift.String = Swift.String()

  /// Optional. is_translate_native_pdf_only field for external customers.
  /// If true, the page limit of online native pdf translation is 300 and only
  /// native pdf pages will be translated.
  public var isTranslateNativePdfOnly: Swift.Bool = Swift.Bool()

  /// Optional. If true, use the text removal server to remove the shadow text on
  /// background image for native pdf translation.
  /// Shadow removal feature can only be enabled when
  /// is_translate_native_pdf_only: false && pdf_native_only: false
  public var enableShadowRemovalNativePdf: Swift.Bool = Swift.Bool()

  /// Optional. If true, enable auto rotation correction in DVS.
  public var enableRotationCorrection: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TranslateDocumentRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TranslateDocumentRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let sourceLanguageCode = CodingKeys(stringValue: "sourceLanguageCode")
    static let targetLanguageCode = CodingKeys(stringValue: "targetLanguageCode")
    static let documentInputConfig = CodingKeys(stringValue: "documentInputConfig")
    static let documentOutputConfig = CodingKeys(stringValue: "documentOutputConfig")
    static let model = CodingKeys(stringValue: "model")
    static let glossaryConfig = CodingKeys(stringValue: "glossaryConfig")
    static let labels = CodingKeys(stringValue: "labels")
    static let customizedAttribution = CodingKeys(stringValue: "customizedAttribution")
    static let isTranslateNativePdfOnly = CodingKeys(stringValue: "isTranslateNativePdfOnly")
    static let enableShadowRemovalNativePdf = CodingKeys(
      stringValue: "enableShadowRemovalNativePdf")
    static let enableRotationCorrection = CodingKeys(stringValue: "enableRotationCorrection")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "sourceLanguageCode",
      "targetLanguageCode",
      "documentInputConfig",
      "documentOutputConfig",
      "model",
      "glossaryConfig",
      "labels",
      "customizedAttribution",
      "isTranslateNativePdfOnly",
      "enableShadowRemovalNativePdf",
      "enableRotationCorrection",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceLanguageCode) {
      self.sourceLanguageCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetLanguageCode) {
      self.targetLanguageCode = value
    }
    self.documentInputConfig = try container.decodeIfPresent(
      DocumentInputConfig.self, forKey: .documentInputConfig)
    self.documentOutputConfig = try container.decodeIfPresent(
      DocumentOutputConfig.self, forKey: .documentOutputConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
      self.model = value
    }
    self.glossaryConfig = try container.decodeIfPresent(
      TranslateTextGlossaryConfig.self, forKey: .glossaryConfig)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customizedAttribution)
    {
      self.customizedAttribution = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isTranslateNativePdfOnly)
    {
      self.isTranslateNativePdfOnly = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableShadowRemovalNativePdf)
    {
      self.enableShadowRemovalNativePdf = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableRotationCorrection)
    {
      self.enableRotationCorrection = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.sourceLanguageCode, forKey: .sourceLanguageCode)
    try container.encode(self.targetLanguageCode, forKey: .targetLanguageCode)
    try container.encodeIfPresent(self.documentInputConfig, forKey: .documentInputConfig)
    try container.encodeIfPresent(self.documentOutputConfig, forKey: .documentOutputConfig)
    try container.encode(self.model, forKey: .model)
    try container.encodeIfPresent(self.glossaryConfig, forKey: .glossaryConfig)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.customizedAttribution, forKey: .customizedAttribution)
    try container.encode(self.isTranslateNativePdfOnly, forKey: .isTranslateNativePdfOnly)
    try container.encode(self.enableShadowRemovalNativePdf, forKey: .enableShadowRemovalNativePdf)
    try container.encode(self.enableRotationCorrection, forKey: .enableRotationCorrection)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.TranslateDocumentRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
