// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Provides natural language translation operations.
///
/// @Snippet(path: "TranslationServiceQuickstart")
public final class TranslationServiceClient: Clients.TranslationServiceProtocol, Sendable {
  let inner: any Clients.TranslationServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `TranslationServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.TranslationServiceStub = try Clients.TranslationServiceTransport(options)
    inner = Clients.TranslationServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TranslationServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Translates input text and returns translated text.
  ///
  /// @Snippet(path: "TranslationService_TranslateText")
  public func translateText(
    request: TranslateTextRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.TranslateTextResponse {
    try await self.inner.translateText(request: request, options: options)
  }

  /// Romanize input text written in non-Latin scripts to Latin text.
  ///
  /// @Snippet(path: "TranslationService_RomanizeText")
  public func romanizeText(
    request: RomanizeTextRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.RomanizeTextResponse {
    try await self.inner.romanizeText(request: request, options: options)
  }

  /// Detects the language of text within a request.
  ///
  /// @Snippet(path: "TranslationService_DetectLanguage")
  public func detectLanguage(
    request: DetectLanguageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.DetectLanguageResponse {
    try await self.inner.detectLanguage(request: request, options: options)
  }

  /// Returns a list of supported languages for translation.
  ///
  /// @Snippet(path: "TranslationService_GetSupportedLanguages")
  public func getSupportedLanguages(
    request: GetSupportedLanguagesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.SupportedLanguages {
    try await self.inner.getSupportedLanguages(request: request, options: options)
  }

  /// Translates documents in synchronous mode.
  ///
  /// @Snippet(path: "TranslationService_TranslateDocument")
  public func translateDocument(
    request: TranslateDocumentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.TranslateDocumentResponse {
    try await self.inner.translateDocument(request: request, options: options)
  }

  /// Translates a large volume of text in asynchronous batch mode.
  /// This function provides real-time output as the inputs are being processed.
  /// If caller cancels a request, the partial results (for an input file, it's
  /// all or nothing) may still be available on the specified output location.
  ///
  /// This call returns immediately and you can
  /// use google.longrunning.Operation.name to poll the status of the call.
  ///
  /// @Snippet(path: "TranslationService_BatchTranslateText")
  public func batchTranslateText(
    request: BatchTranslateTextRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchTranslateText(request: request, options: options)
  }

  /// Translates a large volume of text in asynchronous batch mode.
  /// This function provides real-time output as the inputs are being processed.
  /// If caller cancels a request, the partial results (for an input file, it's
  /// all or nothing) may still be available on the specified output location.
  ///
  /// This call returns immediately and you can
  /// use google.longrunning.Operation.name to poll the status of the call.
  ///
  /// @Snippet(path: "TranslationService_BatchTranslateText")
  public func batchTranslateTextPollingUntilDone(
    request: BatchTranslateTextRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<BatchTranslateResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<BatchTranslateResponse>.State in
      return try op._extractStatus(BatchTranslateResponse.self)
    }
    let rawOp = try await self.batchTranslateText(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<BatchTranslateResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Translates a large volume of document in asynchronous batch mode.
  /// This function provides real-time output as the inputs are being processed.
  /// If caller cancels a request, the partial results (for an input file, it's
  /// all or nothing) may still be available on the specified output location.
  ///
  /// This call returns immediately and you can use
  /// google.longrunning.Operation.name to poll the status of the call.
  ///
  /// @Snippet(path: "TranslationService_BatchTranslateDocument")
  public func batchTranslateDocument(
    request: BatchTranslateDocumentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchTranslateDocument(request: request, options: options)
  }

  /// Translates a large volume of document in asynchronous batch mode.
  /// This function provides real-time output as the inputs are being processed.
  /// If caller cancels a request, the partial results (for an input file, it's
  /// all or nothing) may still be available on the specified output location.
  ///
  /// This call returns immediately and you can use
  /// google.longrunning.Operation.name to poll the status of the call.
  ///
  /// @Snippet(path: "TranslationService_BatchTranslateDocument")
  public func batchTranslateDocumentPollingUntilDone(
    request: BatchTranslateDocumentRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<BatchTranslateDocumentResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<BatchTranslateDocumentResponse>.State in
      return try op._extractStatus(BatchTranslateDocumentResponse.self)
    }
    let rawOp = try await self.batchTranslateDocument(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<BatchTranslateDocumentResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a glossary and returns the long-running operation. Returns
  /// NOT_FOUND, if the project doesn't exist.
  ///
  /// @Snippet(path: "TranslationService_CreateGlossary")
  public func createGlossary(
    request: CreateGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createGlossary(request: request, options: options)
  }

  /// Creates a glossary and returns the long-running operation. Returns
  /// NOT_FOUND, if the project doesn't exist.
  ///
  /// @Snippet(path: "TranslationService_CreateGlossary")
  public func createGlossaryPollingUntilDone(
    request: CreateGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Glossary> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Glossary>.State
      in
      return try op._extractStatus(Glossary.self)
    }
    let rawOp = try await self.createGlossary(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Glossary>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a glossary. A LRO is used since the update can be async if the
  /// glossary's entry file is updated.
  ///
  /// @Snippet(path: "TranslationService_UpdateGlossary")
  public func updateGlossary(
    request: UpdateGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateGlossary(request: request, options: options)
  }

  /// Updates a glossary. A LRO is used since the update can be async if the
  /// glossary's entry file is updated.
  ///
  /// @Snippet(path: "TranslationService_UpdateGlossary")
  public func updateGlossaryPollingUntilDone(
    request: UpdateGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Glossary> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Glossary>.State
      in
      return try op._extractStatus(Glossary.self)
    }
    let rawOp = try await self.updateGlossary(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Glossary>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists glossaries in a project. Returns NOT_FOUND, if the project doesn't
  /// exist.
  ///
  /// @Snippet(path: "TranslationService_ListGlossaries")
  public func listGlossaries(
    request: ListGlossariesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListGlossariesResponse {
    try await self.inner.listGlossaries(request: request, options: options)
  }

  /// Gets a glossary. Returns NOT_FOUND, if the glossary doesn't
  /// exist.
  ///
  /// @Snippet(path: "TranslationService_GetGlossary")
  public func getGlossary(
    request: GetGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.Glossary {
    try await self.inner.getGlossary(request: request, options: options)
  }

  /// Deletes a glossary, or cancels glossary construction
  /// if the glossary isn't created yet.
  /// Returns NOT_FOUND, if the glossary doesn't exist.
  ///
  /// @Snippet(path: "TranslationService_DeleteGlossary")
  public func deleteGlossary(
    request: DeleteGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteGlossary(request: request, options: options)
  }

  /// Deletes a glossary, or cancels glossary construction
  /// if the glossary isn't created yet.
  /// Returns NOT_FOUND, if the glossary doesn't exist.
  ///
  /// @Snippet(path: "TranslationService_DeleteGlossary")
  public func deleteGlossaryPollingUntilDone(
    request: DeleteGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DeleteGlossaryResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DeleteGlossaryResponse>.State in
      return try op._extractStatus(DeleteGlossaryResponse.self)
    }
    let rawOp = try await self.deleteGlossary(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<DeleteGlossaryResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a single glossary entry by the given id.
  ///
  /// @Snippet(path: "TranslationService_GetGlossaryEntry")
  public func getGlossaryEntry(
    request: GetGlossaryEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    try await self.inner.getGlossaryEntry(request: request, options: options)
  }

  /// List the entries for the glossary.
  ///
  /// @Snippet(path: "TranslationService_ListGlossaryEntries")
  public func listGlossaryEntries(
    request: ListGlossaryEntriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse {
    try await self.inner.listGlossaryEntries(request: request, options: options)
  }

  /// Creates a glossary entry.
  ///
  /// @Snippet(path: "TranslationService_CreateGlossaryEntry")
  public func createGlossaryEntry(
    request: CreateGlossaryEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    try await self.inner.createGlossaryEntry(request: request, options: options)
  }

  /// Updates a glossary entry.
  ///
  /// @Snippet(path: "TranslationService_UpdateGlossaryEntry")
  public func updateGlossaryEntry(
    request: UpdateGlossaryEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    try await self.inner.updateGlossaryEntry(request: request, options: options)
  }

  /// Deletes a single entry from the glossary
  ///
  /// @Snippet(path: "TranslationService_DeleteGlossaryEntry")
  public func deleteGlossaryEntry(
    request: DeleteGlossaryEntryRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteGlossaryEntry(request: request, options: options)
  }

  /// Creates a Dataset.
  ///
  /// @Snippet(path: "TranslationService_CreateDataset")
  public func createDataset(
    request: CreateDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createDataset(request: request, options: options)
  }

  /// Creates a Dataset.
  ///
  /// @Snippet(path: "TranslationService_CreateDataset")
  public func createDatasetPollingUntilDone(
    request: CreateDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Dataset> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Dataset>.State in
      return try op._extractStatus(Dataset.self)
    }
    let rawOp = try await self.createDataset(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Dataset>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a Dataset.
  ///
  /// @Snippet(path: "TranslationService_GetDataset")
  public func getDataset(
    request: GetDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.Dataset {
    try await self.inner.getDataset(request: request, options: options)
  }

  /// Lists datasets.
  ///
  /// @Snippet(path: "TranslationService_ListDatasets")
  public func listDatasets(
    request: ListDatasetsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListDatasetsResponse {
    try await self.inner.listDatasets(request: request, options: options)
  }

  /// Deletes a dataset and all of its contents.
  ///
  /// @Snippet(path: "TranslationService_DeleteDataset")
  public func deleteDataset(
    request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteDataset(request: request, options: options)
  }

  /// Deletes a dataset and all of its contents.
  ///
  /// @Snippet(path: "TranslationService_DeleteDataset")
  public func deleteDatasetPollingUntilDone(
    request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteDataset(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates an Adaptive MT dataset.
  ///
  /// @Snippet(path: "TranslationService_CreateAdaptiveMtDataset")
  public func createAdaptiveMtDataset(
    request: CreateAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
    try await self.inner.createAdaptiveMtDataset(request: request, options: options)
  }

  /// Deletes an Adaptive MT dataset, including all its entries and associated
  /// metadata.
  ///
  /// @Snippet(path: "TranslationService_DeleteAdaptiveMtDataset")
  public func deleteAdaptiveMtDataset(
    request: DeleteAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAdaptiveMtDataset(request: request, options: options)
  }

  /// Gets the Adaptive MT dataset.
  ///
  /// @Snippet(path: "TranslationService_GetAdaptiveMtDataset")
  public func getAdaptiveMtDataset(
    request: GetAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
    try await self.inner.getAdaptiveMtDataset(request: request, options: options)
  }

  /// Lists all Adaptive MT datasets for which the caller has read permission.
  ///
  /// @Snippet(path: "TranslationService_ListAdaptiveMtDatasets")
  public func listAdaptiveMtDatasets(
    request: ListAdaptiveMtDatasetsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse {
    try await self.inner.listAdaptiveMtDatasets(request: request, options: options)
  }

  /// Translate text using Adaptive MT.
  ///
  /// @Snippet(path: "TranslationService_AdaptiveMtTranslate")
  public func adaptiveMtTranslate(
    request: AdaptiveMtTranslateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse {
    try await self.inner.adaptiveMtTranslate(request: request, options: options)
  }

  /// Gets and AdaptiveMtFile
  ///
  /// @Snippet(path: "TranslationService_GetAdaptiveMtFile")
  public func getAdaptiveMtFile(
    request: GetAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtFile {
    try await self.inner.getAdaptiveMtFile(request: request, options: options)
  }

  /// Deletes an AdaptiveMtFile along with its sentences.
  ///
  /// @Snippet(path: "TranslationService_DeleteAdaptiveMtFile")
  public func deleteAdaptiveMtFile(
    request: DeleteAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAdaptiveMtFile(request: request, options: options)
  }

  /// Imports an AdaptiveMtFile and adds all of its sentences into the
  /// AdaptiveMtDataset.
  ///
  /// @Snippet(path: "TranslationService_ImportAdaptiveMtFile")
  public func importAdaptiveMtFile(
    request: ImportAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse {
    try await self.inner.importAdaptiveMtFile(request: request, options: options)
  }

  /// Lists all AdaptiveMtFiles associated to an AdaptiveMtDataset.
  ///
  /// @Snippet(path: "TranslationService_ListAdaptiveMtFiles")
  public func listAdaptiveMtFiles(
    request: ListAdaptiveMtFilesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse {
    try await self.inner.listAdaptiveMtFiles(request: request, options: options)
  }

  /// Lists all AdaptiveMtSentences under a given file/dataset.
  ///
  /// @Snippet(path: "TranslationService_ListAdaptiveMtSentences")
  public func listAdaptiveMtSentences(
    request: ListAdaptiveMtSentencesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse {
    try await self.inner.listAdaptiveMtSentences(request: request, options: options)
  }

  /// Import sentence pairs into translation Dataset.
  ///
  /// @Snippet(path: "TranslationService_ImportData")
  public func importData(
    request: ImportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.importData(request: request, options: options)
  }

  /// Import sentence pairs into translation Dataset.
  ///
  /// @Snippet(path: "TranslationService_ImportData")
  public func importDataPollingUntilDone(
    request: ImportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.importData(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Exports dataset's data to the provided output location.
  ///
  /// @Snippet(path: "TranslationService_ExportData")
  public func exportData(
    request: ExportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportData(request: request, options: options)
  }

  /// Exports dataset's data to the provided output location.
  ///
  /// @Snippet(path: "TranslationService_ExportData")
  public func exportDataPollingUntilDone(
    request: ExportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.exportData(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists sentence pairs in the dataset.
  ///
  /// @Snippet(path: "TranslationService_ListExamples")
  public func listExamples(
    request: ListExamplesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListExamplesResponse {
    try await self.inner.listExamples(request: request, options: options)
  }

  /// Creates a Model.
  ///
  /// @Snippet(path: "TranslationService_CreateModel")
  public func createModel(
    request: CreateModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createModel(request: request, options: options)
  }

  /// Creates a Model.
  ///
  /// @Snippet(path: "TranslationService_CreateModel")
  public func createModelPollingUntilDone(
    request: CreateModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Model> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Model>.State in
      return try op._extractStatus(Model.self)
    }
    let rawOp = try await self.createModel(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Model>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists models.
  ///
  /// @Snippet(path: "TranslationService_ListModels")
  public func listModels(
    request: ListModelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListModelsResponse {
    try await self.inner.listModels(request: request, options: options)
  }

  /// Gets a model.
  ///
  /// @Snippet(path: "TranslationService_GetModel")
  public func getModel(
    request: GetModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.Model {
    try await self.inner.getModel(request: request, options: options)
  }

  /// Deletes a model.
  ///
  /// @Snippet(path: "TranslationService_DeleteModel")
  public func deleteModel(
    request: DeleteModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteModel(request: request, options: options)
  }

  /// Deletes a model.
  ///
  /// @Snippet(path: "TranslationService_DeleteModel")
  public func deleteModelPollingUntilDone(
    request: DeleteModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteModel(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "TranslationService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "TranslationService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TranslationService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TranslationService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TranslationService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TranslationService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TranslationService_WaitOperation")
  public func waitOperation(
    request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.waitOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TranslationServiceClient`.
  ///
  /// To mock `TranslationServiceClient` change your functions to receive
  /// `some TranslationServiceProtocol` or `any TranslationServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TranslationServiceProtocol: Sendable {
    /// See `TranslationServiceClient.batchTranslateText`.
    func batchTranslateTextPollingUntilDone(request: BatchTranslateTextRequest) async throws
      -> any GoogleGax.PollableOperation<BatchTranslateResponse>

    /// See `TranslationServiceClient.batchTranslateDocument`.
    func batchTranslateDocumentPollingUntilDone(request: BatchTranslateDocumentRequest) async throws
      -> any GoogleGax.PollableOperation<BatchTranslateDocumentResponse>

    /// See `TranslationServiceClient.batchTranslateDocument`.
    func batchTranslateDocumentPollingUntilDone(
      parent: Swift.String,
      sourceLanguageCode: Swift.String,
      targetLanguageCodes: [Swift.String],
      inputConfigs: [BatchDocumentInputConfig],
      outputConfig: BatchDocumentOutputConfig?,
    ) async throws -> any GoogleGax.PollableOperation<BatchTranslateDocumentResponse>

    /// See `TranslationServiceClient.createGlossary`.
    func createGlossaryPollingUntilDone(request: CreateGlossaryRequest) async throws
      -> any GoogleGax.PollableOperation<Glossary>

    /// See `TranslationServiceClient.createGlossary`.
    func createGlossaryPollingUntilDone(
      parent: Swift.String,
      glossary: Glossary?,
    ) async throws -> any GoogleGax.PollableOperation<Glossary>

    /// See `TranslationServiceClient.updateGlossary`.
    func updateGlossaryPollingUntilDone(request: UpdateGlossaryRequest) async throws
      -> any GoogleGax.PollableOperation<Glossary>

    /// See `TranslationServiceClient.updateGlossary`.
    func updateGlossaryPollingUntilDone(
      glossary: Glossary?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Glossary>

    /// See `TranslationServiceClient.deleteGlossary`.
    func deleteGlossaryPollingUntilDone(request: DeleteGlossaryRequest) async throws
      -> any GoogleGax.PollableOperation<DeleteGlossaryResponse>

    /// See `TranslationServiceClient.deleteGlossary`.
    func deleteGlossaryPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<DeleteGlossaryResponse>

    /// See `TranslationServiceClient.createDataset`.
    func createDatasetPollingUntilDone(request: CreateDatasetRequest) async throws -> any GoogleGax
      .PollableOperation<Dataset>

    /// See `TranslationServiceClient.createDataset`.
    func createDatasetPollingUntilDone(
      parent: Swift.String,
      dataset: Dataset?,
    ) async throws -> any GoogleGax.PollableOperation<Dataset>

    /// See `TranslationServiceClient.deleteDataset`.
    func deleteDatasetPollingUntilDone(request: DeleteDatasetRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.deleteDataset`.
    func deleteDatasetPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.importData`.
    func importDataPollingUntilDone(request: ImportDataRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.importData`.
    func importDataPollingUntilDone(
      dataset: Swift.String,
      inputConfig: DatasetInputConfig?,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.exportData`.
    func exportDataPollingUntilDone(request: ExportDataRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.exportData`.
    func exportDataPollingUntilDone(
      dataset: Swift.String,
      outputConfig: DatasetOutputConfig?,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.createModel`.
    func createModelPollingUntilDone(request: CreateModelRequest) async throws -> any GoogleGax
      .PollableOperation<Model>

    /// See `TranslationServiceClient.createModel`.
    func createModelPollingUntilDone(
      parent: Swift.String,
      model: Model?,
    ) async throws -> any GoogleGax.PollableOperation<Model>

    /// See `TranslationServiceClient.deleteModel`.
    func deleteModelPollingUntilDone(request: DeleteModelRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.deleteModel`.
    func deleteModelPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.translateText`.
    func translateText(
      request: TranslateTextRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.TranslateTextResponse

    /// See `TranslationServiceClient.romanizeText`.
    func romanizeText(
      request: RomanizeTextRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.RomanizeTextResponse

    /// See `TranslationServiceClient.detectLanguage`.
    func detectLanguage(
      request: DetectLanguageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.DetectLanguageResponse

    /// See `TranslationServiceClient.getSupportedLanguages`.
    func getSupportedLanguages(
      request: GetSupportedLanguagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.SupportedLanguages

    /// See `TranslationServiceClient.translateDocument`.
    func translateDocument(
      request: TranslateDocumentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.TranslateDocumentResponse

    /// See `TranslationServiceClient.batchTranslateText`.
    func batchTranslateText(
      request: BatchTranslateTextRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.batchTranslateText`.
    func batchTranslateTextPollingUntilDone(
      request: BatchTranslateTextRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<BatchTranslateResponse>

    /// See `TranslationServiceClient.batchTranslateDocument`.
    func batchTranslateDocument(
      request: BatchTranslateDocumentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.batchTranslateDocument`.
    func batchTranslateDocumentPollingUntilDone(
      request: BatchTranslateDocumentRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<BatchTranslateDocumentResponse>

    /// See `TranslationServiceClient.createGlossary`.
    func createGlossary(
      request: CreateGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.createGlossary`.
    func createGlossaryPollingUntilDone(
      request: CreateGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Glossary>

    /// See `TranslationServiceClient.updateGlossary`.
    func updateGlossary(
      request: UpdateGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.updateGlossary`.
    func updateGlossaryPollingUntilDone(
      request: UpdateGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Glossary>

    /// See `TranslationServiceClient.listGlossaries`.
    func listGlossaries(
      request: ListGlossariesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListGlossariesResponse

    /// See `TranslationServiceClient.getGlossary`.
    func getGlossary(
      request: GetGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Glossary

    /// See `TranslationServiceClient.deleteGlossary`.
    func deleteGlossary(
      request: DeleteGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.deleteGlossary`.
    func deleteGlossaryPollingUntilDone(
      request: DeleteGlossaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<DeleteGlossaryResponse>

    /// See `TranslationServiceClient.getGlossaryEntry`.
    func getGlossaryEntry(
      request: GetGlossaryEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry

    /// See `TranslationServiceClient.listGlossaryEntries`.
    func listGlossaryEntries(
      request: ListGlossaryEntriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse

    /// See `TranslationServiceClient.createGlossaryEntry`.
    func createGlossaryEntry(
      request: CreateGlossaryEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry

    /// See `TranslationServiceClient.updateGlossaryEntry`.
    func updateGlossaryEntry(
      request: UpdateGlossaryEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.GlossaryEntry

    /// See `TranslationServiceClient.deleteGlossaryEntry`.
    func deleteGlossaryEntry(
      request: DeleteGlossaryEntryRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TranslationServiceClient.createDataset`.
    func createDataset(
      request: CreateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.createDataset`.
    func createDatasetPollingUntilDone(
      request: CreateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Dataset>

    /// See `TranslationServiceClient.getDataset`.
    func getDataset(
      request: GetDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Dataset

    /// See `TranslationServiceClient.listDatasets`.
    func listDatasets(
      request: ListDatasetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListDatasetsResponse

    /// See `TranslationServiceClient.deleteDataset`.
    func deleteDataset(
      request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.deleteDataset`.
    func deleteDatasetPollingUntilDone(
      request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.createAdaptiveMtDataset`.
    func createAdaptiveMtDataset(
      request: CreateAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset

    /// See `TranslationServiceClient.deleteAdaptiveMtDataset`.
    func deleteAdaptiveMtDataset(
      request: DeleteAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TranslationServiceClient.getAdaptiveMtDataset`.
    func getAdaptiveMtDataset(
      request: GetAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset

    /// See `TranslationServiceClient.listAdaptiveMtDatasets`.
    func listAdaptiveMtDatasets(
      request: ListAdaptiveMtDatasetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse

    /// See `TranslationServiceClient.adaptiveMtTranslate`.
    func adaptiveMtTranslate(
      request: AdaptiveMtTranslateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse

    /// See `TranslationServiceClient.getAdaptiveMtFile`.
    func getAdaptiveMtFile(
      request: GetAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.AdaptiveMtFile

    /// See `TranslationServiceClient.deleteAdaptiveMtFile`.
    func deleteAdaptiveMtFile(
      request: DeleteAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TranslationServiceClient.importAdaptiveMtFile`.
    func importAdaptiveMtFile(
      request: ImportAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse

    /// See `TranslationServiceClient.listAdaptiveMtFiles`.
    func listAdaptiveMtFiles(
      request: ListAdaptiveMtFilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse

    /// See `TranslationServiceClient.listAdaptiveMtSentences`.
    func listAdaptiveMtSentences(
      request: ListAdaptiveMtSentencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse

    /// See `TranslationServiceClient.importData`.
    func importData(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.importData`.
    func importDataPollingUntilDone(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.exportData`.
    func exportData(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.exportData`.
    func exportDataPollingUntilDone(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.listExamples`.
    func listExamples(
      request: ListExamplesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListExamplesResponse

    /// See `TranslationServiceClient.createModel`.
    func createModel(
      request: CreateModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.createModel`.
    func createModelPollingUntilDone(
      request: CreateModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Model>

    /// See `TranslationServiceClient.listModels`.
    func listModels(
      request: ListModelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.ListModelsResponse

    /// See `TranslationServiceClient.getModel`.
    func getModel(
      request: GetModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTranslateV3.Model

    /// See `TranslationServiceClient.deleteModel`.
    func deleteModel(
      request: DeleteModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TranslationServiceClient.deleteModel`.
    func deleteModelPollingUntilDone(
      request: DeleteModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `TranslationServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `TranslationServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `TranslationServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `TranslationServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TranslationServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TranslationServiceClient.waitOperation`.
    func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}

// Default implementations
extension Clients.TranslationServiceProtocol {
  public func translateText(request: TranslateTextRequest) async throws
    -> GoogleCloudTranslateV3.TranslateTextResponse
  {
    try await self.translateText(request: request, options: .init())
  }

  public func translateText(
    request: TranslateTextRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.TranslateTextResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func translateText(
    parent: Swift.String,
    targetLanguageCode: Swift.String,
    contents: [Swift.String],
  ) async throws -> GoogleCloudTranslateV3.TranslateTextResponse {
    let request = TranslateTextRequest().with {
      $0.parent = parent
      $0.targetLanguageCode = targetLanguageCode
      $0.contents = contents
    }
    return try await self.translateText(request: request)
  }

  public func translateText(
    parent: Swift.String,
    model: Swift.String,
    mimeType: Swift.String,
    sourceLanguageCode: Swift.String,
    targetLanguageCode: Swift.String,
    contents: [Swift.String],
  ) async throws -> GoogleCloudTranslateV3.TranslateTextResponse {
    let request = TranslateTextRequest().with {
      $0.parent = parent
      $0.model = model
      $0.mimeType = mimeType
      $0.sourceLanguageCode = sourceLanguageCode
      $0.targetLanguageCode = targetLanguageCode
      $0.contents = contents
    }
    return try await self.translateText(request: request)
  }

  public func romanizeText(request: RomanizeTextRequest) async throws
    -> GoogleCloudTranslateV3.RomanizeTextResponse
  {
    try await self.romanizeText(request: request, options: .init())
  }

  public func romanizeText(
    request: RomanizeTextRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.RomanizeTextResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func romanizeText(
    parent: Swift.String,
    contents: [Swift.String],
  ) async throws -> GoogleCloudTranslateV3.RomanizeTextResponse {
    let request = RomanizeTextRequest().with {
      $0.parent = parent
      $0.contents = contents
    }
    return try await self.romanizeText(request: request)
  }

  public func detectLanguage(request: DetectLanguageRequest) async throws
    -> GoogleCloudTranslateV3.DetectLanguageResponse
  {
    try await self.detectLanguage(request: request, options: .init())
  }

  public func detectLanguage(
    request: DetectLanguageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.DetectLanguageResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func detectLanguage(
    parent: Swift.String,
    model: Swift.String,
    mimeType: Swift.String,
    content: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.DetectLanguageResponse {
    let request = DetectLanguageRequest().with {
      $0.parent = parent
      $0.model = model
      $0.mimeType = mimeType
      $0.source = .content(content)
    }
    return try await self.detectLanguage(request: request)
  }

  public func getSupportedLanguages(request: GetSupportedLanguagesRequest) async throws
    -> GoogleCloudTranslateV3.SupportedLanguages
  {
    try await self.getSupportedLanguages(request: request, options: .init())
  }

  public func getSupportedLanguages(
    request: GetSupportedLanguagesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.SupportedLanguages {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSupportedLanguages(
    parent: Swift.String,
    model: Swift.String,
    displayLanguageCode: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.SupportedLanguages {
    let request = GetSupportedLanguagesRequest().with {
      $0.parent = parent
      $0.model = model
      $0.displayLanguageCode = displayLanguageCode
    }
    return try await self.getSupportedLanguages(request: request)
  }

  public func translateDocument(request: TranslateDocumentRequest) async throws
    -> GoogleCloudTranslateV3.TranslateDocumentResponse
  {
    try await self.translateDocument(request: request, options: .init())
  }

  public func translateDocument(
    request: TranslateDocumentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.TranslateDocumentResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchTranslateText(request: BatchTranslateTextRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchTranslateText(request: request, options: .init())
  }

  public func batchTranslateText(
    request: BatchTranslateTextRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchTranslateTextPollingUntilDone(request: BatchTranslateTextRequest) async throws
    -> any GoogleGax.PollableOperation<BatchTranslateResponse>
  {
    try await self.batchTranslateTextPollingUntilDone(request: request, options: .init())
  }

  public func batchTranslateTextPollingUntilDone(
    request: BatchTranslateTextRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<BatchTranslateResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<BatchTranslateResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func batchTranslateDocument(request: BatchTranslateDocumentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchTranslateDocument(request: request, options: .init())
  }

  public func batchTranslateDocument(
    request: BatchTranslateDocumentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchTranslateDocumentPollingUntilDone(request: BatchTranslateDocumentRequest)
    async throws -> any GoogleGax.PollableOperation<BatchTranslateDocumentResponse>
  {
    try await self.batchTranslateDocumentPollingUntilDone(request: request, options: .init())
  }

  public func batchTranslateDocumentPollingUntilDone(
    request: BatchTranslateDocumentRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<BatchTranslateDocumentResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<BatchTranslateDocumentResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func batchTranslateDocumentPollingUntilDone(
    parent: Swift.String,
    sourceLanguageCode: Swift.String,
    targetLanguageCodes: [Swift.String],
    inputConfigs: [BatchDocumentInputConfig],
    outputConfig: BatchDocumentOutputConfig?,
  ) async throws -> any GoogleGax.PollableOperation<BatchTranslateDocumentResponse> {
    let request = BatchTranslateDocumentRequest().with {
      $0.parent = parent
      $0.sourceLanguageCode = sourceLanguageCode
      $0.targetLanguageCodes = targetLanguageCodes
      $0.inputConfigs = inputConfigs
      $0.outputConfig = outputConfig
    }
    return try await self.batchTranslateDocumentPollingUntilDone(request: request)
  }

  public func createGlossary(request: CreateGlossaryRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createGlossary(request: request, options: .init())
  }

  public func createGlossary(
    request: CreateGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createGlossaryPollingUntilDone(request: CreateGlossaryRequest) async throws
    -> any GoogleGax.PollableOperation<Glossary>
  {
    try await self.createGlossaryPollingUntilDone(request: request, options: .init())
  }

  public func createGlossaryPollingUntilDone(
    request: CreateGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Glossary> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Glossary>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createGlossaryPollingUntilDone(
    parent: Swift.String,
    glossary: Glossary?,
  ) async throws -> any GoogleGax.PollableOperation<Glossary> {
    let request = CreateGlossaryRequest().with {
      $0.parent = parent
      $0.glossary = glossary
    }
    return try await self.createGlossaryPollingUntilDone(request: request)
  }

  public func updateGlossary(request: UpdateGlossaryRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateGlossary(request: request, options: .init())
  }

  public func updateGlossary(
    request: UpdateGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateGlossaryPollingUntilDone(request: UpdateGlossaryRequest) async throws
    -> any GoogleGax.PollableOperation<Glossary>
  {
    try await self.updateGlossaryPollingUntilDone(request: request, options: .init())
  }

  public func updateGlossaryPollingUntilDone(
    request: UpdateGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Glossary> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Glossary>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateGlossaryPollingUntilDone(
    glossary: Glossary?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Glossary> {
    let request = UpdateGlossaryRequest().with {
      $0.glossary = glossary
      $0.updateMask = updateMask
    }
    return try await self.updateGlossaryPollingUntilDone(request: request)
  }

  public func listGlossaries(request: ListGlossariesRequest) async throws
    -> GoogleCloudTranslateV3.ListGlossariesResponse
  {
    try await self.listGlossaries(request: request, options: .init())
  }

  public func listGlossaries(
    request: ListGlossariesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListGlossariesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listGlossaries(
    byItem: ListGlossariesRequest
  ) -> any AsyncSequence<Glossary, Swift.Error> {
    self.listGlossaries(byItem: byItem, options: .init())
  }

  /// Lists glossaries in a project. Returns NOT_FOUND, if the project doesn't
  /// exist.
  ///
  /// @Snippet(path: "TranslationService_ListGlossaries")
  public func listGlossaries(
    byItem: ListGlossariesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Glossary, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTranslateV3.ListGlossariesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listGlossaries(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGlossaries(
    parent: Swift.String,
  ) -> any AsyncSequence<Glossary, Swift.Error> {
    let request = ListGlossariesRequest().with {
      $0.parent = parent
    }
    return self.listGlossaries(byItem: request)
  }

  public func getGlossary(request: GetGlossaryRequest) async throws
    -> GoogleCloudTranslateV3.Glossary
  {
    try await self.getGlossary(request: request, options: .init())
  }

  public func getGlossary(
    request: GetGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.Glossary {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getGlossary(
    name: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.Glossary {
    let request = GetGlossaryRequest().with {
      $0.name = name
    }
    return try await self.getGlossary(request: request)
  }

  public func deleteGlossary(request: DeleteGlossaryRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteGlossary(request: request, options: .init())
  }

  public func deleteGlossary(
    request: DeleteGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteGlossaryPollingUntilDone(request: DeleteGlossaryRequest) async throws
    -> any GoogleGax.PollableOperation<DeleteGlossaryResponse>
  {
    try await self.deleteGlossaryPollingUntilDone(request: request, options: .init())
  }

  public func deleteGlossaryPollingUntilDone(
    request: DeleteGlossaryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DeleteGlossaryResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<DeleteGlossaryResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteGlossaryPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<DeleteGlossaryResponse> {
    let request = DeleteGlossaryRequest().with {
      $0.name = name
    }
    return try await self.deleteGlossaryPollingUntilDone(request: request)
  }

  public func getGlossaryEntry(request: GetGlossaryEntryRequest) async throws
    -> GoogleCloudTranslateV3.GlossaryEntry
  {
    try await self.getGlossaryEntry(request: request, options: .init())
  }

  public func getGlossaryEntry(
    request: GetGlossaryEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getGlossaryEntry(
    name: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    let request = GetGlossaryEntryRequest().with {
      $0.name = name
    }
    return try await self.getGlossaryEntry(request: request)
  }

  public func listGlossaryEntries(request: ListGlossaryEntriesRequest) async throws
    -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse
  {
    try await self.listGlossaryEntries(request: request, options: .init())
  }

  public func listGlossaryEntries(
    request: ListGlossaryEntriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listGlossaryEntries(
    byItem: ListGlossaryEntriesRequest
  ) -> any AsyncSequence<GlossaryEntry, Swift.Error> {
    self.listGlossaryEntries(byItem: byItem, options: .init())
  }

  /// List the entries for the glossary.
  ///
  /// @Snippet(path: "TranslationService_ListGlossaryEntries")
  public func listGlossaryEntries(
    byItem: ListGlossaryEntriesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GlossaryEntry, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTranslateV3.ListGlossaryEntriesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listGlossaryEntries(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGlossaryEntries(
    parent: Swift.String,
  ) -> any AsyncSequence<GlossaryEntry, Swift.Error> {
    let request = ListGlossaryEntriesRequest().with {
      $0.parent = parent
    }
    return self.listGlossaryEntries(byItem: request)
  }

  public func createGlossaryEntry(request: CreateGlossaryEntryRequest) async throws
    -> GoogleCloudTranslateV3.GlossaryEntry
  {
    try await self.createGlossaryEntry(request: request, options: .init())
  }

  public func createGlossaryEntry(
    request: CreateGlossaryEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createGlossaryEntry(
    parent: Swift.String,
    glossaryEntry: GlossaryEntry?,
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    let request = CreateGlossaryEntryRequest().with {
      $0.parent = parent
      $0.glossaryEntry = glossaryEntry
    }
    return try await self.createGlossaryEntry(request: request)
  }

  public func updateGlossaryEntry(request: UpdateGlossaryEntryRequest) async throws
    -> GoogleCloudTranslateV3.GlossaryEntry
  {
    try await self.updateGlossaryEntry(request: request, options: .init())
  }

  public func updateGlossaryEntry(
    request: UpdateGlossaryEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateGlossaryEntry(
    glossaryEntry: GlossaryEntry?,
  ) async throws -> GoogleCloudTranslateV3.GlossaryEntry {
    let request = UpdateGlossaryEntryRequest().with {
      $0.glossaryEntry = glossaryEntry
    }
    return try await self.updateGlossaryEntry(request: request)
  }

  public func deleteGlossaryEntry(request: DeleteGlossaryEntryRequest) async throws {
    try await self.deleteGlossaryEntry(request: request, options: .init())
  }

  public func deleteGlossaryEntry(
    request: DeleteGlossaryEntryRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteGlossaryEntry(
    name: Swift.String,
  ) async throws {
    let request = DeleteGlossaryEntryRequest().with {
      $0.name = name
    }
    try await self.deleteGlossaryEntry(request: request)
  }

  public func createDataset(request: CreateDatasetRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createDataset(request: request, options: .init())
  }

  public func createDataset(
    request: CreateDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createDatasetPollingUntilDone(request: CreateDatasetRequest) async throws
    -> any GoogleGax.PollableOperation<Dataset>
  {
    try await self.createDatasetPollingUntilDone(request: request, options: .init())
  }

  public func createDatasetPollingUntilDone(
    request: CreateDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Dataset> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Dataset>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createDatasetPollingUntilDone(
    parent: Swift.String,
    dataset: Dataset?,
  ) async throws -> any GoogleGax.PollableOperation<Dataset> {
    let request = CreateDatasetRequest().with {
      $0.parent = parent
      $0.dataset = dataset
    }
    return try await self.createDatasetPollingUntilDone(request: request)
  }

  public func getDataset(request: GetDatasetRequest) async throws -> GoogleCloudTranslateV3.Dataset
  {
    try await self.getDataset(request: request, options: .init())
  }

  public func getDataset(
    request: GetDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.Dataset {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDataset(
    name: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.Dataset {
    let request = GetDatasetRequest().with {
      $0.name = name
    }
    return try await self.getDataset(request: request)
  }

  public func listDatasets(request: ListDatasetsRequest) async throws
    -> GoogleCloudTranslateV3.ListDatasetsResponse
  {
    try await self.listDatasets(request: request, options: .init())
  }

  public func listDatasets(
    request: ListDatasetsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListDatasetsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDatasets(
    byItem: ListDatasetsRequest
  ) -> any AsyncSequence<Dataset, Swift.Error> {
    self.listDatasets(byItem: byItem, options: .init())
  }

  /// Lists datasets.
  ///
  /// @Snippet(path: "TranslationService_ListDatasets")
  public func listDatasets(
    byItem: ListDatasetsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Dataset, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTranslateV3.ListDatasetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDatasets(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDatasets(
    parent: Swift.String,
  ) -> any AsyncSequence<Dataset, Swift.Error> {
    let request = ListDatasetsRequest().with {
      $0.parent = parent
    }
    return self.listDatasets(byItem: request)
  }

  public func deleteDataset(request: DeleteDatasetRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteDataset(request: request, options: .init())
  }

  public func deleteDataset(
    request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteDatasetPollingUntilDone(request: DeleteDatasetRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteDatasetPollingUntilDone(request: request, options: .init())
  }

  public func deleteDatasetPollingUntilDone(
    request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteDatasetPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteDatasetRequest().with {
      $0.name = name
    }
    return try await self.deleteDatasetPollingUntilDone(request: request)
  }

  public func createAdaptiveMtDataset(request: CreateAdaptiveMtDatasetRequest) async throws
    -> GoogleCloudTranslateV3.AdaptiveMtDataset
  {
    try await self.createAdaptiveMtDataset(request: request, options: .init())
  }

  public func createAdaptiveMtDataset(
    request: CreateAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAdaptiveMtDataset(
    parent: Swift.String,
    adaptiveMtDataset: AdaptiveMtDataset?,
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
    let request = CreateAdaptiveMtDatasetRequest().with {
      $0.parent = parent
      $0.adaptiveMtDataset = adaptiveMtDataset
    }
    return try await self.createAdaptiveMtDataset(request: request)
  }

  public func deleteAdaptiveMtDataset(request: DeleteAdaptiveMtDatasetRequest) async throws {
    try await self.deleteAdaptiveMtDataset(request: request, options: .init())
  }

  public func deleteAdaptiveMtDataset(
    request: DeleteAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAdaptiveMtDataset(
    name: Swift.String,
  ) async throws {
    let request = DeleteAdaptiveMtDatasetRequest().with {
      $0.name = name
    }
    try await self.deleteAdaptiveMtDataset(request: request)
  }

  public func getAdaptiveMtDataset(request: GetAdaptiveMtDatasetRequest) async throws
    -> GoogleCloudTranslateV3.AdaptiveMtDataset
  {
    try await self.getAdaptiveMtDataset(request: request, options: .init())
  }

  public func getAdaptiveMtDataset(
    request: GetAdaptiveMtDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAdaptiveMtDataset(
    name: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtDataset {
    let request = GetAdaptiveMtDatasetRequest().with {
      $0.name = name
    }
    return try await self.getAdaptiveMtDataset(request: request)
  }

  public func listAdaptiveMtDatasets(request: ListAdaptiveMtDatasetsRequest) async throws
    -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse
  {
    try await self.listAdaptiveMtDatasets(request: request, options: .init())
  }

  public func listAdaptiveMtDatasets(
    request: ListAdaptiveMtDatasetsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAdaptiveMtDatasets(
    byItem: ListAdaptiveMtDatasetsRequest
  ) -> any AsyncSequence<AdaptiveMtDataset, Swift.Error> {
    self.listAdaptiveMtDatasets(byItem: byItem, options: .init())
  }

  /// Lists all Adaptive MT datasets for which the caller has read permission.
  ///
  /// @Snippet(path: "TranslationService_ListAdaptiveMtDatasets")
  public func listAdaptiveMtDatasets(
    byItem: ListAdaptiveMtDatasetsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AdaptiveMtDataset, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtDatasetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAdaptiveMtDatasets(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAdaptiveMtDatasets(
    parent: Swift.String,
  ) -> any AsyncSequence<AdaptiveMtDataset, Swift.Error> {
    let request = ListAdaptiveMtDatasetsRequest().with {
      $0.parent = parent
    }
    return self.listAdaptiveMtDatasets(byItem: request)
  }

  public func adaptiveMtTranslate(request: AdaptiveMtTranslateRequest) async throws
    -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse
  {
    try await self.adaptiveMtTranslate(request: request, options: .init())
  }

  public func adaptiveMtTranslate(
    request: AdaptiveMtTranslateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func adaptiveMtTranslate(
    parent: Swift.String,
    content: [Swift.String],
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtTranslateResponse {
    let request = AdaptiveMtTranslateRequest().with {
      $0.parent = parent
      $0.content = content
    }
    return try await self.adaptiveMtTranslate(request: request)
  }

  public func getAdaptiveMtFile(request: GetAdaptiveMtFileRequest) async throws
    -> GoogleCloudTranslateV3.AdaptiveMtFile
  {
    try await self.getAdaptiveMtFile(request: request, options: .init())
  }

  public func getAdaptiveMtFile(
    request: GetAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtFile {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAdaptiveMtFile(
    name: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.AdaptiveMtFile {
    let request = GetAdaptiveMtFileRequest().with {
      $0.name = name
    }
    return try await self.getAdaptiveMtFile(request: request)
  }

  public func deleteAdaptiveMtFile(request: DeleteAdaptiveMtFileRequest) async throws {
    try await self.deleteAdaptiveMtFile(request: request, options: .init())
  }

  public func deleteAdaptiveMtFile(
    request: DeleteAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAdaptiveMtFile(
    name: Swift.String,
  ) async throws {
    let request = DeleteAdaptiveMtFileRequest().with {
      $0.name = name
    }
    try await self.deleteAdaptiveMtFile(request: request)
  }

  public func importAdaptiveMtFile(request: ImportAdaptiveMtFileRequest) async throws
    -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse
  {
    try await self.importAdaptiveMtFile(request: request, options: .init())
  }

  public func importAdaptiveMtFile(
    request: ImportAdaptiveMtFileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func importAdaptiveMtFile(
    parent: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.ImportAdaptiveMtFileResponse {
    let request = ImportAdaptiveMtFileRequest().with {
      $0.parent = parent
    }
    return try await self.importAdaptiveMtFile(request: request)
  }

  public func listAdaptiveMtFiles(request: ListAdaptiveMtFilesRequest) async throws
    -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse
  {
    try await self.listAdaptiveMtFiles(request: request, options: .init())
  }

  public func listAdaptiveMtFiles(
    request: ListAdaptiveMtFilesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAdaptiveMtFiles(
    byItem: ListAdaptiveMtFilesRequest
  ) -> any AsyncSequence<AdaptiveMtFile, Swift.Error> {
    self.listAdaptiveMtFiles(byItem: byItem, options: .init())
  }

  /// Lists all AdaptiveMtFiles associated to an AdaptiveMtDataset.
  ///
  /// @Snippet(path: "TranslationService_ListAdaptiveMtFiles")
  public func listAdaptiveMtFiles(
    byItem: ListAdaptiveMtFilesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AdaptiveMtFile, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtFilesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAdaptiveMtFiles(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAdaptiveMtFiles(
    parent: Swift.String,
  ) -> any AsyncSequence<AdaptiveMtFile, Swift.Error> {
    let request = ListAdaptiveMtFilesRequest().with {
      $0.parent = parent
    }
    return self.listAdaptiveMtFiles(byItem: request)
  }

  public func listAdaptiveMtSentences(request: ListAdaptiveMtSentencesRequest) async throws
    -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse
  {
    try await self.listAdaptiveMtSentences(request: request, options: .init())
  }

  public func listAdaptiveMtSentences(
    request: ListAdaptiveMtSentencesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAdaptiveMtSentences(
    byItem: ListAdaptiveMtSentencesRequest
  ) -> any AsyncSequence<AdaptiveMtSentence, Swift.Error> {
    self.listAdaptiveMtSentences(byItem: byItem, options: .init())
  }

  /// Lists all AdaptiveMtSentences under a given file/dataset.
  ///
  /// @Snippet(path: "TranslationService_ListAdaptiveMtSentences")
  public func listAdaptiveMtSentences(
    byItem: ListAdaptiveMtSentencesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AdaptiveMtSentence, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTranslateV3.ListAdaptiveMtSentencesResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listAdaptiveMtSentences(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAdaptiveMtSentences(
    parent: Swift.String,
  ) -> any AsyncSequence<AdaptiveMtSentence, Swift.Error> {
    let request = ListAdaptiveMtSentencesRequest().with {
      $0.parent = parent
    }
    return self.listAdaptiveMtSentences(byItem: request)
  }

  public func importData(request: ImportDataRequest) async throws -> GoogleLongRunning.Operation {
    try await self.importData(request: request, options: .init())
  }

  public func importData(
    request: ImportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func importDataPollingUntilDone(request: ImportDataRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.importDataPollingUntilDone(request: request, options: .init())
  }

  public func importDataPollingUntilDone(
    request: ImportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func importDataPollingUntilDone(
    dataset: Swift.String,
    inputConfig: DatasetInputConfig?,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = ImportDataRequest().with {
      $0.dataset = dataset
      $0.inputConfig = inputConfig
    }
    return try await self.importDataPollingUntilDone(request: request)
  }

  public func exportData(request: ExportDataRequest) async throws -> GoogleLongRunning.Operation {
    try await self.exportData(request: request, options: .init())
  }

  public func exportData(
    request: ExportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func exportDataPollingUntilDone(request: ExportDataRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.exportDataPollingUntilDone(request: request, options: .init())
  }

  public func exportDataPollingUntilDone(
    request: ExportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func exportDataPollingUntilDone(
    dataset: Swift.String,
    outputConfig: DatasetOutputConfig?,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = ExportDataRequest().with {
      $0.dataset = dataset
      $0.outputConfig = outputConfig
    }
    return try await self.exportDataPollingUntilDone(request: request)
  }

  public func listExamples(request: ListExamplesRequest) async throws
    -> GoogleCloudTranslateV3.ListExamplesResponse
  {
    try await self.listExamples(request: request, options: .init())
  }

  public func listExamples(
    request: ListExamplesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListExamplesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listExamples(
    byItem: ListExamplesRequest
  ) -> any AsyncSequence<Example, Swift.Error> {
    self.listExamples(byItem: byItem, options: .init())
  }

  /// Lists sentence pairs in the dataset.
  ///
  /// @Snippet(path: "TranslationService_ListExamples")
  public func listExamples(
    byItem: ListExamplesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Example, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTranslateV3.ListExamplesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listExamples(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listExamples(
    parent: Swift.String,
  ) -> any AsyncSequence<Example, Swift.Error> {
    let request = ListExamplesRequest().with {
      $0.parent = parent
    }
    return self.listExamples(byItem: request)
  }

  public func createModel(request: CreateModelRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createModel(request: request, options: .init())
  }

  public func createModel(
    request: CreateModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createModelPollingUntilDone(request: CreateModelRequest) async throws -> any GoogleGax
    .PollableOperation<Model>
  {
    try await self.createModelPollingUntilDone(request: request, options: .init())
  }

  public func createModelPollingUntilDone(
    request: CreateModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Model> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Model>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createModelPollingUntilDone(
    parent: Swift.String,
    model: Model?,
  ) async throws -> any GoogleGax.PollableOperation<Model> {
    let request = CreateModelRequest().with {
      $0.parent = parent
      $0.model = model
    }
    return try await self.createModelPollingUntilDone(request: request)
  }

  public func listModels(request: ListModelsRequest) async throws
    -> GoogleCloudTranslateV3.ListModelsResponse
  {
    try await self.listModels(request: request, options: .init())
  }

  public func listModels(
    request: ListModelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.ListModelsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listModels(
    byItem: ListModelsRequest
  ) -> any AsyncSequence<Model, Swift.Error> {
    self.listModels(byItem: byItem, options: .init())
  }

  /// Lists models.
  ///
  /// @Snippet(path: "TranslationService_ListModels")
  public func listModels(
    byItem: ListModelsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Model, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTranslateV3.ListModelsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listModels(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listModels(
    parent: Swift.String,
  ) -> any AsyncSequence<Model, Swift.Error> {
    let request = ListModelsRequest().with {
      $0.parent = parent
    }
    return self.listModels(byItem: request)
  }

  public func getModel(request: GetModelRequest) async throws -> GoogleCloudTranslateV3.Model {
    try await self.getModel(request: request, options: .init())
  }

  public func getModel(
    request: GetModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTranslateV3.Model {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getModel(
    name: Swift.String,
  ) async throws -> GoogleCloudTranslateV3.Model {
    let request = GetModelRequest().with {
      $0.name = name
    }
    return try await self.getModel(request: request)
  }

  public func deleteModel(request: DeleteModelRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteModel(request: request, options: .init())
  }

  public func deleteModel(
    request: DeleteModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteModelPollingUntilDone(request: DeleteModelRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteModelPollingUntilDone(request: request, options: .init())
  }

  public func deleteModelPollingUntilDone(
    request: DeleteModelRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteModelPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteModelRequest().with {
      $0.name = name
    }
    return try await self.deleteModelPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "TranslationService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TranslationService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }

  public func waitOperation(request: GoogleLongRunning.WaitOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.waitOperation(request: request, options: .init())
  }

  public func waitOperation(
    request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }
}
