// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A translated document response message.
public struct TranslateDocumentResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Translated document.
  public var documentTranslation: DocumentTranslation? = nil

  /// The document's translation output if a glossary is provided in the request.
  /// This can be the same as [TranslateDocumentResponse.document_translation]
  /// if no glossary terms apply.
  public var glossaryDocumentTranslation: DocumentTranslation? = nil

  /// Only present when 'model' is present in the request.
  /// 'model' is normalized to have a project number.
  ///
  /// For example:
  /// If the 'model' field in TranslateDocumentRequest is:
  /// `projects/{project-id}/locations/{location-id}/models/general/nmt` then
  /// `model` here would be normalized to
  /// `projects/{project-number}/locations/{location-id}/models/general/nmt`.
  public var model: Swift.String = Swift.String()

  /// The `glossary_config` used for this translation.
  public var glossaryConfig: TranslateTextGlossaryConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TranslateDocumentResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TranslateDocumentResponse().with { $0.documentTranslation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let documentTranslation = CodingKeys(stringValue: "documentTranslation")
    static let glossaryDocumentTranslation = CodingKeys(stringValue: "glossaryDocumentTranslation")
    static let model = CodingKeys(stringValue: "model")
    static let glossaryConfig = CodingKeys(stringValue: "glossaryConfig")

    static let _knownKeys: Set<Swift.String> = [
      "documentTranslation",
      "glossaryDocumentTranslation",
      "model",
      "glossaryConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.documentTranslation = try container.decodeIfPresent(
      DocumentTranslation.self, forKey: .documentTranslation)
    self.glossaryDocumentTranslation = try container.decodeIfPresent(
      DocumentTranslation.self, forKey: .glossaryDocumentTranslation)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
      self.model = value
    }
    self.glossaryConfig = try container.decodeIfPresent(
      TranslateTextGlossaryConfig.self, forKey: .glossaryConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.documentTranslation, forKey: .documentTranslation)
    try container.encodeIfPresent(
      self.glossaryDocumentTranslation, forKey: .glossaryDocumentTranslation)
    try container.encode(self.model, forKey: .model)
    try container.encodeIfPresent(self.glossaryConfig, forKey: .glossaryConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.translation.v3.TranslateDocumentResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
